-- Behavioral checks on deployed database. Every fixture and assignment change is rolled back.
begin;
select set_config('atwar.kpi.employee',(select id::text from public.profiles where full_name='اختبار E2E - موظف'),true);
select set_config('atwar.kpi.manager',(select id::text from public.profiles where full_name='اختبار E2E - مدير'),true);
select set_config('atwar.kpi.admin',(select id::text from public.profiles where full_name='اختبار E2E - مدير نظام'),true);
select set_config('atwar.kpi.outsider',(select id::text from public.profiles where role='employee' and active and status='active' and id<>current_setting('atwar.kpi.employee')::uuid and manager_id is distinct from current_setting('atwar.kpi.manager')::uuid order by id limit 1),true);
select set_config('atwar.kpi.job',(select id::text from public.job_descriptions where published_snapshot is not null and jsonb_array_length(published_snapshot->'content'->'kpis')>0 order by id limit 1),true);
select set_config('atwar.kpi.published_before',(select md5(published_snapshot::text||content::text) from public.job_descriptions where id=current_setting('atwar.kpi.job')::uuid),true);
select set_config('request.jwt.claim.sub',current_setting('atwar.kpi.admin'),true);
update public.profiles set job_description_id=current_setting('atwar.kpi.job')::uuid where id=current_setting('atwar.kpi.employee')::uuid;
set local role authenticated;
do $$ declare e uuid:=current_setting('atwar.kpi.employee')::uuid;m uuid:=current_setting('atwar.kpi.manager')::uuid;o uuid:=current_setting('atwar.kpi.outsider')::uuid;j uuid:=current_setting('atwar.kpi.job')::uuid;rid uuid:=gen_random_uuid();ctx jsonb;v jsonb;d jsonb;revision integer;t uuid;hidden_task uuid;
begin
 perform set_config('request.jwt.claim.sub',e::text,true);
 ctx:=public.kpi_measurement_context(e);revision:=(ctx->'job'->>'revision')::integer;
 if (ctx->'job'->>'id')::uuid<>j or revision is null then raise exception 'Published KPI context is unavailable';end if;
 perform set_config('atwar.kpi.indicator',(ctx->'job'->'indicators'->0)::text,true);
 t:=public.create_task_safe('QA KPI link rollback',e);
 d:=jsonb_build_object('period_start','2026-10-01','period_end','2026-10-31','result_text','95%','task_id',t);
 v:=public.save_kpi_measurement(rid,e,j,revision,0,0,d);
 if (v->>'revision')::integer<>1 or v->'indicator_snapshot' is distinct from ctx->'job'->'indicators'->0 then raise exception 'Wrong saved indicator snapshot';end if;
 if not exists(select 1 from public.kpi_measurements where id=rid) then raise exception 'Own record unreadable';end if;
 begin perform public.save_kpi_measurement(rid,e,j,revision,0,0,d);raise exception 'Stale result accepted';exception when serialization_failure then null;end;
 begin perform public.save_kpi_measurement(gen_random_uuid(),e,j,revision,0,0,d);raise exception 'Duplicate period accepted';exception when serialization_failure then null;end;
 begin perform public.save_kpi_measurement(gen_random_uuid(),e,j,revision+1,0,0,d);raise exception 'Stale published revision accepted';exception when serialization_failure then null;end;
 begin perform public.save_kpi_measurement(rid,e,j,revision,1,1,d);raise exception 'Indicator identity changed';exception when insufficient_privilege then null;end;
 begin perform public.save_kpi_measurement(rid,e,j,revision,0,1,d||'{"weight":100}');raise exception 'Unsupported score definition accepted';exception when invalid_parameter_value then null;end;
 begin perform public.save_kpi_measurement(rid,e,j,revision,0,1,d||'{"period_end":"2026-09-30"}');raise exception 'Invalid period accepted';exception when invalid_parameter_value then null;end;
 begin perform public.save_kpi_measurement(rid,e,j,revision,0,1,d||'{"evidence_url":"javascript:alert(1)"}');raise exception 'Unsafe evidence URL accepted';exception when check_violation then null;end;
 begin perform public.save_kpi_measurement(rid,e,j,revision,0,1,d||jsonb_build_object('project_id',gen_random_uuid()));raise exception 'Invisible project linked';exception when insufficient_privilege then null;end;
 begin update public.kpi_measurements set result_text='tamper' where id=rid;raise exception 'Direct result update accepted';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claim.sub',m::text,true);
 hidden_task:=public.create_task_safe('QA manager private KPI reference',m);
 v:=public.save_kpi_measurement(rid,e,j,revision,0,1,d||jsonb_build_object('source_text','Reviewed source','evidence_note','Report reference'));
 if (v->>'revision')::integer<>2 then raise exception 'Manager update failed';end if;
 perform set_config('request.jwt.claim.sub',e::text,true);
 begin perform public.save_kpi_measurement(rid,e,j,revision,0,2,d||jsonb_build_object('task_id',hidden_task));raise exception 'Invisible task linked';exception when insufficient_privilege then null;end;
 perform set_config('atwar.kpi.record',rid::text,true);perform set_config('atwar.kpi.revision',revision::text,true);perform set_config('atwar.kpi.task',t::text,true);
 perform set_config('request.jwt.claim.sub',o::text,true);
 if exists(select 1 from public.kpi_measurements where id=rid) then raise exception 'Outsider measurement leak';end if;
 begin perform public.kpi_measurement_context(e);raise exception 'Outsider context accepted';exception when insufficient_privilege then null;end;
 begin perform public.save_kpi_measurement(rid,e,j,revision,0,2,d);raise exception 'Outsider update accepted';exception when insufficient_privilege then null;end;
 if has_table_privilege('anon','public.kpi_measurements','SELECT') or has_function_privilege('anon','public.save_kpi_measurement(uuid,uuid,uuid,integer,integer,integer,jsonb)','EXECUTE') then raise exception 'Anonymous grants';end if;
end $$;
reset role;
select set_config('request.jwt.claim.sub',current_setting('atwar.kpi.admin'),true);
update public.profiles set job_description_id=null where id=current_setting('atwar.kpi.employee')::uuid;
set local role authenticated;
select set_config('request.jwt.claim.sub',current_setting('atwar.kpi.employee'),true);
do $$ declare e uuid:=current_setting('atwar.kpi.employee')::uuid;j uuid:=current_setting('atwar.kpi.job')::uuid;rid uuid:=current_setting('atwar.kpi.record')::uuid;v jsonb;
begin
 v:=public.save_kpi_measurement(rid,e,j,current_setting('atwar.kpi.revision')::integer,0,2,jsonb_build_object('period_start','2026-10-01','period_end','2026-10-31','result_text','96%','source_text','Historical period source','task_id',current_setting('atwar.kpi.task')));
 if (v->>'revision')::integer<>3 or v->'indicator_snapshot' is distinct from current_setting('atwar.kpi.indicator')::jsonb then raise exception 'Historical snapshot changed';end if;

end $$;
reset role;
do $$ begin if (select count(*) from public.admin_audit_log where action='KPI_MEASUREMENT' and target_id=current_setting('atwar.kpi.record'))<>3 then raise exception 'Measurement audit missing';end if;end $$;
select case when (select md5(published_snapshot::text||content::text) from public.job_descriptions where id=current_setting('atwar.kpi.job')::uuid)=current_setting('atwar.kpi.published_before') then 'PASS: own/manager saves, snapshot preservation, historical edits, stale revisions, duplicate periods, link scope, unsafe URLs, direct-write denial, outsider isolation and unchanged KPI definitions' else 'FAIL: published definitions changed' end result;
rollback;
