begin;
create temporary table qa_policy(p uuid,v uuid,v2 uuid,a uuid,m uuid,e uuid,other uuid);
insert into qa_policy(a,m,e,other) select (select id from public.profiles where email='e2e-admin@atwargroup.test'),(select id from public.profiles where email='e2e-manager@atwargroup.test'),(select id from public.profiles where email='e2e-employee@atwargroup.test'),(select id from public.profiles where role='employee' and email<>'e2e-employee@atwargroup.test' and active=true and status='active' limit 1);
grant all on qa_policy to authenticated;
set local role authenticated;
select set_config('request.jwt.claims',jsonb_build_object('sub',a,'role','authenticated')::text,true) from qa_policy;
update qa_policy set p=public.policy_create('QA-'||gen_random_uuid()::text,'QA Policy','[{"id":"s1","title":"Test section","body":"Original text"}]','QA');
update qa_policy set v=(select id from public.policy_versions where policy_id=p);
select public.policy_configure(p,1,'QA Policy',a,m,a,m,array['EMPLOYEES'],array[]::uuid[]) from qa_policy;
do $$ declare c record;v record;begin select * into c from qa_policy;select * into v from public.policy_versions where id=c.v;
 if v.current_task_id is null then raise exception 'Missing preparation task';end if;
 begin update public.policy_versions set status='APPROVED' where id=c.v;raise exception 'Direct update permitted';exception when insufficient_privilege then null;end;
 begin update public.tasks set status='مكتملة',progress=100 where id=v.current_task_id;exception when insufficient_privilege then null;end;
 if (select status from public.tasks where id=v.current_task_id)='مكتملة' then raise exception 'Manual completion permitted';end if;
 begin perform public.policy_save(c.v,1,'[{"id":"s1","title":"Test section","body":"Stale edit"}]','QA');raise exception 'Stale save accepted';exception when raise_exception then if sqlerrm not like 'ATWAR_CONFLICT:%' then raise;end if;end;
end $$;
select public.policy_decide(v,2,false,'Prepared for review',null) from qa_policy;
select set_config('request.jwt.claims',jsonb_build_object('sub',e,'role','authenticated')::text,true) from qa_policy;
do $$ declare c record;begin select * into c from qa_policy;
 if exists(select 1 from public.policies where id=c.p) then raise exception 'Draft exposed to employee';end if;
 begin perform public.policy_decide(c.v,3,false,'Employee decision',null);raise exception 'Employee advanced';exception when insufficient_privilege then null;end;
 begin perform public.policy_directory();raise exception 'Directory exposed';exception when insufficient_privilege then null;end;
end $$;
select set_config('request.jwt.claims',jsonb_build_object('sub',a,'role','authenticated')::text,true) from qa_policy;
do $$ declare c record;begin select * into c from qa_policy;
 begin perform public.policy_decide(c.v,3,false,'Admin bypass',null);raise exception 'Admin bypassed assigned reviewer';exception when insufficient_privilege then null;end;
end $$;
select set_config('request.jwt.claims',jsonb_build_object('sub',m,'role','authenticated')::text,true) from qa_policy;
select public.policy_comment(v,'s1','Please clarify wording') from qa_policy;
select public.policy_decide(v,3,true,'Needs wording change',null) from qa_policy;
select set_config('request.jwt.claims',jsonb_build_object('sub',a,'role','authenticated')::text,true) from qa_policy;
select public.policy_save(v,4,'[{"id":"s1","title":"Test section","body":"Revised text"}]','QA revised') from qa_policy;
select public.policy_decide(v,5,false,'Prepared updated text',null) from qa_policy;
select set_config('request.jwt.claims',jsonb_build_object('sub',m,'role','authenticated')::text,true) from qa_policy;
select public.policy_decide(v,6,false,'Review completed',null) from qa_policy;
select set_config('request.jwt.claims',jsonb_build_object('sub',a,'role','authenticated')::text,true) from qa_policy;
select public.policy_decide(v,7,false,'Approval completed',null) from qa_policy;
select set_config('request.jwt.claims',jsonb_build_object('sub',m,'role','authenticated')::text,true) from qa_policy;
select public.policy_decide(v,8,false,'Ratified for today',current_date) from qa_policy;
select set_config('request.jwt.claims',jsonb_build_object('sub',e,'role','authenticated')::text,true) from qa_policy;
do $$ declare c record;begin select * into c from qa_policy;
 if not exists(select 1 from public.policy_versions where id=c.v and content->0->>'body'='Revised text') then raise exception 'Published missing';end if;
 if exists(select 1 from public.policy_comments where version_id=c.v) or exists(select 1 from public.policy_events where policy_id=c.p) then raise exception 'Internal review exposed';end if;
end $$;
select set_config('request.jwt.claims',jsonb_build_object('sub',a,'role','authenticated')::text,true) from qa_policy;
do $$ declare c record;begin select * into c from qa_policy;
 begin perform public.policy_save(c.v,9,'[{"id":"s1","title":"Test section","body":"Overwrite approved"}]','Bad');raise exception 'Approved mutated';exception when raise_exception then if sqlerrm not like 'Editing is allowed%' then raise;end if;end;
 if (select count(*) from public.tasks where legacy_metadata->'job_workflow'->>'policy_id'=c.p::text and status<>'مكتملة')<>0 then raise exception 'Closed stage tasks remain open';end if;
end $$;
update qa_policy set v2=public.policy_new_version(p,2);
select public.policy_configure(p,3,'QA Policy',a,a,a,a,array['MANAGEMENT'],array[m]) from qa_policy;
select public.policy_save(v2,2,'[{"id":"s1","title":"Test section","body":"Future text"}]','Future QA') from qa_policy;
select public.policy_decide(v2,3,false,'Preparation completed',null) from qa_policy;
select public.policy_decide(v2,4,false,'Review completed',null) from qa_policy;
select public.policy_decide(v2,5,false,'Approval completed',null) from qa_policy;
select public.policy_decide(v2,6,false,'Future ratification',current_date+1) from qa_policy;
select set_config('request.jwt.claims',jsonb_build_object('sub',e,'role','authenticated')::text,true) from qa_policy;
do $$ declare c record;begin select * into c from qa_policy;
 if not exists(select 1 from public.policy_versions where id=c.v) or exists(select 1 from public.policy_versions where id=c.v2) then raise exception 'Future version replaced current or leaked';end if;
end $$;
-- Move future date to today as database owner, to exercise audience switching.
reset role;
update public.policy_versions set effective_date=current_date where id=(select v2 from qa_policy);
set local role authenticated;
do $$ declare c record;begin select * into c from qa_policy;
 if exists(select 1 from public.policies where id=c.p) or exists(select 1 from public.policy_versions where policy_id=c.p) then raise exception 'Previous employee audience retained';end if;
end $$;
select set_config('request.jwt.claims',jsonb_build_object('sub',m,'role','authenticated')::text,true) from qa_policy;
do $$ declare c record;begin select * into c from qa_policy;
 if not exists(select 1 from public.policy_versions where id=c.v2) or exists(select 1 from public.policy_versions where id=c.v) then raise exception 'Management audience or old version visibility failed';end if;
end $$;
select set_config('request.jwt.claims',jsonb_build_object('sub',other,'role','authenticated')::text,true) from qa_policy;
do $$ declare c record;begin select * into c from qa_policy;
 if exists(select 1 from public.policies where id=c.p) then raise exception 'Unselected audience sees management policy';end if;
end $$;
reset role;
do $$ begin if has_table_privilege('anon','public.policies','SELECT') or has_function_privilege('anon','public.policy_decide(uuid,integer,boolean,text,date)','EXECUTE') then raise exception 'Anonymous access permitted';end if;end $$;
select 'PASS: stage owners, no admin bypass, tasks, returns, comments, stale writes, immutable approved content, audience snapshot and future effective version' as result;
rollback;
