-- Transactional acceptance on the deployed database; all fixtures are rolled back.
begin;
select set_config('atwar.test.manager',(select id::text from public.profiles where full_name='اختبار E2E - مدير' and active and status='active'),true);
select set_config('atwar.test.employee',(select id::text from public.profiles where full_name='اختبار E2E - موظف' and active and status='active'),true);
select set_config('atwar.test.admin',(select id::text from public.profiles where full_name='اختبار E2E - مدير نظام' and active and status='active'),true);
set local role authenticated;
do $$ declare m uuid:=current_setting('atwar.test.manager')::uuid;e uuid:=current_setting('atwar.test.employee')::uuid;a uuid:=current_setting('atwar.test.admin')::uuid;p uuid;t uuid;p2 uuid;p3 uuid;t3 uuid;r integer;versions jsonb;original jsonb;task_row public.tasks%rowtype;
begin
 if m is null or e is null or a is null then raise exception 'Active E2E fixtures are required';end if;
 perform set_config('request.jwt.claim.sub',m::text,true);
 p:=public.project_command(null,0,'create',jsonb_build_object('title','QA rollback baseline','manager_id',m,'sponsor_id',a,'start_date','2026-10-01','due_date','2026-12-31'));
 t:=public.project_command(p,1,'task',jsonb_build_object('title','QA baseline task','assignee_id',m,'start_date','2026-10-02','due_date','2026-10-10'));
 select revision into r from public.projects where id=p;
 select jsonb_build_array(jsonb_build_object('id',id,'revision',revision)) into versions from public.tasks where id=t;
 begin perform public.capture_project_baseline(p,r-1,versions);raise exception 'Stale project revision accepted';exception when serialization_failure then null;end;
 task_row:=public.update_task_safe(t,1,'{"title":"QA baseline task changed"}');
 begin perform public.capture_project_baseline(p,r,versions);raise exception 'Stale task revision accepted';exception when serialization_failure then null;end;
 select jsonb_build_array(jsonb_build_object('id',id,'revision',revision)) into versions from public.tasks where id=t;
 begin perform public.capture_project_baseline(p,r,'[]');raise exception 'Incomplete task snapshot accepted';exception when serialization_failure then null;end;
 perform public.capture_project_baseline(p,r,versions);
 select task_snapshot into original from public.project_baselines where project_id=p;
 if jsonb_array_length(original)<>1 or original->0->>'title'<>'QA baseline task changed' then raise exception 'Wrong original snapshot';end if;
 if (select revision from public.projects where id=p)<>r+1 then raise exception 'Project refresh revision missing';end if;
 if not exists(select 1 from public.project_events where project_id=p and action='BASELINE_CAPTURED') then raise exception 'Baseline audit missing';end if;
 begin perform public.capture_project_baseline(p,r+1,versions);raise exception 'Duplicate original baseline accepted';exception when invalid_parameter_value then null;end;
 task_row:=public.update_task_safe(t,task_row.revision,'{"due_date":"2026-10-12","manager_notes":"QA date change"}');
 if (select task_snapshot from public.project_baselines where project_id=p) is distinct from original then raise exception 'Original snapshot mutated';end if;
 begin update public.project_baselines set captured_by_name='tamper' where project_id=p;raise exception 'Direct baseline update accepted';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claim.sub',e::text,true);
 if exists(select 1 from public.project_baselines where project_id=p) then raise exception 'Outsider baseline leak';end if;
 begin perform public.capture_project_baseline(p,r+1,versions);raise exception 'Outsider capture accepted';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claim.sub',m::text,true);
 perform public.project_command(p,r+1,'members',jsonb_build_object('members',jsonb_build_array(e)));
 perform set_config('request.jwt.claim.sub',e::text,true);
 if not exists(select 1 from public.project_baselines where project_id=p) then raise exception 'Project member baseline inaccessible';end if;
 begin perform public.capture_project_baseline(p,r+2,versions);raise exception 'Member capture accepted';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claim.sub',a::text,true);
 p2:=public.project_command(null,0,'create',jsonb_build_object('title','QA admin baseline','manager_id',m,'sponsor_id',a,'start_date','2026-10-01','due_date','2026-12-31'));
 perform public.capture_project_baseline(p2,1,'[]');
 if not exists(select 1 from public.project_baselines where project_id=p2 and captured_by=a) then raise exception 'Admin capture failed';end if;
 p3:=public.project_command(null,0,'create',jsonb_build_object('title','QA closed baseline','manager_id',m,'sponsor_id',a,'start_date','2026-10-01','due_date','2026-12-31'));
 t3:=public.project_command(p3,1,'task',jsonb_build_object('title','QA close task','assignee_id',m,'start_date','2026-10-02','due_date','2026-10-10'));
 perform set_config('request.jwt.claim.sub',m::text,true);
 task_row:=public.update_task_safe(t3,1,'{"status":"قيد التنفيذ"}');
 task_row:=public.update_task_safe(t3,task_row.revision,'{"status":"بانتظار الاعتماد","progress":100}');
 perform set_config('request.jwt.claim.sub',a::text,true);
 task_row:=public.update_task_safe(t3,task_row.revision,'{"status":"مكتملة"}');
 perform public.project_command(p3,2,'close','{}');
 select revision into r from public.projects where id=p3;
 begin perform public.capture_project_baseline(p3,r,'[]');raise exception 'Closed project baseline accepted';exception when insufficient_privilege then null;end;
 if has_table_privilege('anon','public.project_baselines','SELECT') or has_function_privilege('anon','public.capture_project_baseline(uuid,integer,jsonb)','EXECUTE') then raise exception 'Anonymous baseline grant';end if;
 perform set_config('atwar.test.baseline.result','PASS: manager/admin capture, original preservation, stale project/tasks, incomplete preview, duplicate prevention, audit, member read, outsider isolation, write denial, closed project',true);
end $$;
select current_setting('atwar.test.baseline.result') result;
rollback;
