-- Behavioral acceptance on the deployed database; every fixture is rolled back.
begin;
select set_config('test.admin',(select id::text from public.profiles where role='admin' and active and status='active' limit 1),true);
select set_config('test.manager',(select id::text from public.profiles where role='manager' and active and status='active' limit 1),true);
select set_config('test.employee',(select id::text from public.profiles where role='employee' and active and status='active' order by id limit 1),true);
select set_config('test.outsider',(select id::text from public.profiles where role='employee' and active and status='active' order by id offset 1 limit 1),true);
set local role authenticated;
do $$ declare a uuid:=current_setting('test.admin')::uuid;m uuid:=current_setting('test.manager')::uuid;e uuid:=current_setting('test.employee')::uuid;o uuid:=current_setting('test.outsider')::uuid;p uuid;t1 uuid;t2 uuid;t3 uuid;r integer;rejected boolean;row public.tasks%rowtype;
begin
 perform set_config('request.jwt.claim.sub',a::text,true);
 p:=public.project_command(null,0,'create',jsonb_build_object('title','QA rolled back project','manager_id',m,'sponsor_id',a,'start_date','2026-10-01','due_date','2026-12-31','members',jsonb_build_array(e)));
 if not private.project_access(p) then raise exception 'QA admin access';end if;
 perform set_config('request.jwt.claim.sub',o::text,true);
 if exists(select 1 from public.projects where id=p) then raise exception 'QA outsider project leak';end if;
 rejected:=false;begin perform public.project_command(p,1,'message','{"body":"unauthorized"}');exception when others then rejected:=true;end;if not rejected then raise exception 'QA outsider chat';end if;
 perform set_config('request.jwt.claim.sub',m::text,true);
 t1:=public.project_command(p,1,'task',jsonb_build_object('title','first','assignee_id',e,'start_date','2026-10-02','due_date','2026-10-10','weight',2));
 t2:=public.project_command(p,2,'task',jsonb_build_object('title','second','assignee_id',e,'start_date','2026-10-11','due_date','2026-10-20'));
 perform public.project_command(p,3,'dependency',jsonb_build_object('task_id',t2,'predecessor_id',t1));
 rejected:=false;begin perform public.project_command(p,4,'dependency',jsonb_build_object('task_id',t1,'predecessor_id',t2));exception when others then rejected:=true;end;if not rejected then raise exception 'QA cycle accepted';end if;
 rejected:=false;begin perform public.project_command(p,1,'phase','{"title":"stale"}');exception when others then rejected:=true;end;if not rejected then raise exception 'QA stale project accepted';end if;
 perform set_config('request.jwt.claim.sub',e::text,true);
 if not exists(select 1 from public.tasks where id=t1) then raise exception 'QA member task access';end if;
 perform public.project_command(p,0,'message',jsonb_build_object('body','QA message','mentions',jsonb_build_array(m),'task_id',t1));
 rejected:=false;begin perform public.project_command(p,0,'message',jsonb_build_object('body','QA message','mentions',jsonb_build_array(o)));exception when others then rejected:=true;end;if not rejected then raise exception 'QA outsider mention';end if;
 rejected:=false;begin perform public.update_task_safe(t2,1,'{"status":"قيد التنفيذ"}');exception when others then rejected:=true;end;if not rejected then raise exception 'QA blocked dependency';end if;
 rejected:=false;begin perform public.update_task_safe(t1,1,'{"due_date":"2026-10-09"}');exception when others then rejected:=true;end;if not rejected then raise exception 'QA employee schedule';end if;
 row:=public.update_task_safe(t1,1,'{"status":"قيد التنفيذ"}');
 row:=public.update_task_safe(t1,row.revision,'{"status":"بانتظار الاعتماد","progress":100}');
 rejected:=false;begin perform public.update_task_safe(t1,row.revision,'{"status":"مكتملة"}');exception when others then rejected:=true;end;if not rejected then raise exception 'QA self approval';end if;
 perform set_config('request.jwt.claim.sub',m::text,true);
 row:=public.update_task_safe(t1,row.revision,'{"status":"مكتملة"}');
 if row.approved_by_id<>m then raise exception 'QA approver';end if;
 rejected:=false;begin perform public.update_task_safe(t2,1,'{"due_date":"2026-10-21"}');exception when others then rejected:=true;end;if not rejected then raise exception 'QA schedule missing reason';end if;
 row:=public.update_task_safe(t2,1,'{"due_date":"2026-10-21","manager_notes":"QA schedule reason"}');
 perform set_config('request.jwt.claim.sub',e::text,true);
 row:=public.update_task_safe(t2,row.revision,'{"status":"قيد التنفيذ"}');
 row:=public.update_task_safe(t2,row.revision,'{"status":"بانتظار الاعتماد","progress":100}');
 perform set_config('request.jwt.claim.sub',m::text,true);
 row:=public.update_task_safe(t2,row.revision,'{"status":"مكتملة"}');
 select revision into r from public.projects where id=p;
 t3:=public.project_command(p,r,'task',jsonb_build_object('title','manager task','assignee_id',m,'start_date','2026-10-22','due_date','2026-10-23'));
 row:=public.update_task_safe(t3,1,'{"status":"قيد التنفيذ"}');row:=public.update_task_safe(t3,row.revision,'{"status":"بانتظار الاعتماد","progress":100}');
 rejected:=false;begin perform public.update_task_safe(t3,row.revision,'{"status":"مكتملة"}');exception when others then rejected:=true;end;if not rejected then raise exception 'QA manager self approval';end if;
 select revision into r from public.projects where id=p;
 rejected:=false;begin perform public.project_command(p,r,'close','{}');exception when others then rejected:=true;end;if not rejected then raise exception 'QA manager close';end if;
 perform set_config('request.jwt.claim.sub',a::text,true);
 rejected:=false;begin perform public.project_command(p,r,'close','{}');exception when others then rejected:=true;end;if not rejected then raise exception 'QA premature close';end if;
 row:=public.update_task_safe(t3,row.revision,'{"status":"مكتملة"}');
 perform public.project_command(p,r,'close','{}');
 perform set_config('request.jwt.claim.sub',e::text,true);
 rejected:=false;begin perform public.project_command(p,0,'message','{"body":"closed"}');exception when others then rejected:=true;end;if not rejected then raise exception 'QA closed chat';end if;
 perform set_config('request.jwt.claim.sub',o::text,true);
 if exists(select 1 from public.project_messages where project_id=p) or exists(select 1 from public.project_events where project_id=p) then raise exception 'QA outsider content leak';end if;
 perform set_config('request.jwt.claim.sub',a::text,true);
 t1:=public.create_task_safe('QA ordinary self task',a);select * into row from public.tasks where id=t1;
 if row.completion_requires_approval then raise exception 'QA ordinary task classification regression';end if;
 row:=public.update_task_safe(row.id,row.revision,'{"status":"قيد التنفيذ"}');
 row:=public.update_task_safe(row.id,row.revision,'{"status":"مكتملة"}');
 if row.status<>'مكتملة' then raise exception 'QA ordinary task workflow regression';end if;
 if has_table_privilege('anon','public.projects','SELECT') or has_table_privilege('anon','public.project_messages','SELECT') or has_function_privilege('anon','public.project_command(uuid,integer,text,jsonb)','EXECUTE') then raise exception 'QA anonymous access grant';end if;
 perform set_config('test.project.result','PASS: membership, isolation, chat, mentions, cycles, stale revisions, dependencies, schedule ownership, self approval, sponsor approval, closure',true);
end $$;
select current_setting('test.project.result') as result;
rollback;
