BEGIN;
update profiles set active=true,status='active' where id='2347fbff-372e-43d1-a2e4-094f5b3159bf';
update profiles set manager_id='2347fbff-372e-43d1-a2e4-094f5b3159bf' where id='eabb8105-e54d-45a3-90c8-15334698bbfc';
DO $$ declare t uuid; t2 uuid; r uuid; v public.tasks%rowtype; rev int; n int; begin
perform set_config('request.jwt.claim.sub','797d5893-d44d-489c-9109-91da4882acfe',true);
t:=create_task_safe('اختبار التفويض والإلغاء','2347fbff-372e-43d1-a2e4-094f5b3159bf',p_start_date=>current_date-3,p_due_date=>current_date-1);
select revision into rev from tasks where id=t;
perform set_config('request.jwt.claim.sub','2347fbff-372e-43d1-a2e4-094f5b3159bf',true);
select * into v from delegate_task_safe(t,'eabb8105-e54d-45a3-90c8-15334698bbfc',rev);
if v.delegated_by_id<>'2347fbff-372e-43d1-a2e4-094f5b3159bf' or v.assignee_id<>'eabb8105-e54d-45a3-90c8-15334698bbfc' then raise exception 'delegation state';end if;
select count(*) into n from task_activity where task_id=t;
perform delegate_task_safe(t,'eabb8105-e54d-45a3-90c8-15334698bbfc',rev);
if (select count(*) from task_activity where task_id=t)<>n then raise exception 'replay duplicated activity';end if;
perform set_config('request.jwt.claim.sub','eabb8105-e54d-45a3-90c8-15334698bbfc',true);
begin perform delegate_task_safe(t,'797d5893-d44d-489c-9109-91da4882acfe',v.revision);raise exception 'employee delegated';exception when insufficient_privilege then null;end;
r:=request_task_reschedule(t,current_date,current_date+3,'اختبار إعادة الجدولة');
if (select due_date from tasks where id=t)<>current_date-1 then raise exception 'unapproved schedule changed';end if;
begin perform decide_task_reschedule(r,true,null);raise exception 'requester approved';exception when insufficient_privilege then null;end;
perform set_config('request.jwt.claim.sub','2347fbff-372e-43d1-a2e4-094f5b3159bf',true);
select * into v from delegate_task_safe(t,'2347fbff-372e-43d1-a2e4-094f5b3159bf',v.revision);
if v.delegated_by_id is not null or v.delegated_at is not null or v.delegated_by_name_snapshot is not null then raise exception 'reclaim retained delegation';end if;
if (select status from task_reschedule_requests where id=r)<>'CANCELLED' then raise exception 'old assignee request survived reclaim';end if;
r:=request_task_reschedule(t,current_date,current_date+3,'إعادة جدولة بعد الاسترجاع');
perform set_config('request.jwt.claim.sub','797d5893-d44d-489c-9109-91da4882acfe',true);
perform decide_task_reschedule(r,true,'موافقة الاختبار');
if (select due_date from tasks where id=t)<>current_date+3 or (select status from task_reschedule_requests where id=r)<>'APPROVED' then raise exception 'approved schedule mismatch';end if;
begin perform decide_task_reschedule(r,true,null);raise exception 'request decided twice';exception when raise_exception then if sqlerrm='request decided twice' then raise;end if;end;
perform set_config('request.jwt.claim.sub','2347fbff-372e-43d1-a2e4-094f5b3159bf',true);
r:=request_task_reschedule(t,current_date,current_date+5,'طلب قبل إلغاء المهمة');
perform set_config('request.jwt.claim.sub','797d5893-d44d-489c-9109-91da4882acfe',true);
perform cancel_task_safe(t,'إلغاء مهمة اختبار');
if (select status from task_reschedule_requests where id=r)<>'CANCELLED' then raise exception 'cancel retained pending request';end if;
if current_setting('app.cancel_mode',true)='on' then raise exception 'cancel mode leaked';end if;
perform set_config('request.jwt.claim.sub','2347fbff-372e-43d1-a2e4-094f5b3159bf',true);
begin perform request_task_reschedule(t,current_date,current_date+6,'طلب على مهمة ملغاة');raise exception 'cancelled task rescheduled';exception when raise_exception then if sqlerrm='cancelled task rescheduled' then raise;end if;end;
perform set_config('request.jwt.claim.sub','797d5893-d44d-489c-9109-91da4882acfe',true);
t2:=create_task_safe('اختبار اعتماد وإعادة جدولة','eabb8105-e54d-45a3-90c8-15334698bbfc',p_start_date=>current_date-3,p_due_date=>current_date-1);
perform set_config('request.jwt.claim.sub','eabb8105-e54d-45a3-90c8-15334698bbfc',true);
r:=request_task_reschedule(t2,current_date,current_date+5,'طلب قبل مرحلة الاعتماد');
update tasks set status='قيد التنفيذ' where id=t2;
update tasks set status='بانتظار الاعتماد',progress=100 where id=t2;
if (select status from task_reschedule_requests where id=r)<>'CANCELLED' then raise exception 'approval retained pending request';end if;
begin perform cancel_task_safe(t2,'محاولة غير مخولة');raise exception 'employee cancelled';exception when raise_exception then if sqlerrm='employee cancelled' then raise;end if;end;
execute 'set local role authenticated';
if (select count(*) from tasks where id in(t,t2))<>1 then raise exception 'employee scope leaked reclaimed task';end if;
execute 'reset role';
end $$;
ROLLBACK;
select 'PASS: delegation replay/reclaim, assignee scope, unauthorized calls, reschedule approval/date preservation/stale invalidation, cancellation and independent approval' result;
