import {createRequire} from 'node:module';import {createServer} from 'node:http';import {readFileSync,readdirSync,writeFileSync} from 'node:fs';import {resolve} from 'node:path';
const require=createRequire(import.meta.url);const {chromium}=require(require.resolve('playwright',{paths:[process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES]}));const root=resolve('.');
const walk=d=>readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?['.git','tests','lab'].includes(e.name)?[]:walk(d+'/'+e.name):e.name.endsWith('.html')?[d+'/'+e.name]:[]);
const pages=walk(root).map(p=>p.slice(root.length+1)).filter(p=>!['index.html','completed/index.html','approvals/index.html','follow-up/index.html','my-day/index.html'].includes(p));
const server=createServer((req,res)=>{try{const p=resolve(root,'.'+req.url.split('?')[0]);if(!p.startsWith(root+'/'))throw Error();let body=readFileSync(p);if(p.endsWith('.html')){let s=body.toString().replace(/<script\b[\s\S]*?<\/script>/gi,'');s=s.replace('</head>','<script src="/assets/js/shell-components.js"></script></head>');body=Buffer.from(s);}res.setHeader('content-type',p.endsWith('.js')||p.endsWith('.mjs')?'text/javascript':p.endsWith('.css')?'text/css':p.endsWith('.html')?'text/html':'application/octet-stream');res.end(body);}catch{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({executablePath:'/workspace/scratch/8fa5605f660d/browser-test/chrome-headless-shell-linux64/chrome-headless-shell',headless:true,args:['--no-sandbox']});const results=[];
try{const page=await browser.newPage();await page.route('https://**/*',route=>route.abort());
for(const path of pages){for(const [label,width,height] of [['desktop',1440,1000],['mobile',390,844]]){await page.setViewportSize({width,height});await page.goto(`http://127.0.0.1:${server.address().port}/${path}`,{waitUntil:'domcontentloaded'});await page.evaluate(()=>{document.body.style.visibility='visible';document.body.classList.remove('auth-pending');const login=document.getElementById('loginView');if(login)login.style.display='none';const app=document.getElementById('appView');if(app){app.classList.remove('hidden');app.style.display='block';}window.atwarSyncShellIdentity?.({role:'admin',full_name:'حساب مراجعة التصميم',permissions:[]},{email:'review@example.invalid'});});await page.waitForTimeout(100);const data=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth+2,scrollWidth:document.documentElement.scrollWidth,theme:!!document.querySelector('link[data-atwar-app-theme]'),font:getComputedStyle(document.body).fontFamily,controls:[...document.querySelectorAll('button,input,select')].filter(e=>e.getBoundingClientRect().width>0).length}));const name=path.replaceAll('/','_').replace('.html','')+'_'+label;await page.screenshot({path:`/tmp/atwar-review-screens/${name}.png`});results.push({path,label,...data});}}
writeFileSync('/tmp/atwar-review-screens/results.json',JSON.stringify(results,null,2));console.log(JSON.stringify({screens:pages.length,views:results.length,overflow:results.filter(r=>r.overflow).map(r=>({path:r.path,view:r.label,width:r.scrollWidth})),noTheme:results.filter(r=>r.label==='desktop'&&!r.theme).map(r=>r.path)}));
}finally{await browser.close();server.close();}
