import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {createServer} from 'node:http';
import {readFileSync,existsSync} from 'node:fs';
import {resolve} from 'node:path';
const require=createRequire(import.meta.url);
const {chromium}=require(require.resolve('playwright',{paths:[process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES]}));
const root=resolve('.');
const harness=`<!doctype html><html dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><link rel="stylesheet" href="/assets/css/task-batches.css"></head><body><button id="bulkAssignButton" hidden>إسناد جماعي</button><button id="batchFollowButton" hidden>متابعة</button><script type="module">
import {createTaskBatchesController} from '/assets/js/task-batches.mjs';
window.profile={uid:'admin',role:'admin'};window.calls=[];window.uploads=[];window.refreshed=0;window.messages=[];window.failed=false;window.committed=null;
const people=[{id:'a',full_name:'أحمد',department:'المبيعات'},{id:'b',full_name:'عمر',department:'المبيعات'},{id:'c',full_name:'<img src=x onerror=alert(1)>',department:'الدعم'}];
const sb={async rpc(name,args){calls.push({name,args});if(name==='task_batch_directory')return {data:people};if(name==='create_task_batch_safe'){await new Promise(r=>setTimeout(r,150));committed=args;if(!failed){failed=true;return {error:{message:'انقطع الاتصال بعد حفظ الطلب'}};}return {data:{batch_id:args.p_request_id,count:2}};}return {data:committed?[{id:committed.p_request_id,title:committed.p_title,tasks:[{id:'a',name:'أحمد',status:'بانتظار الاعتماد',progress:100,due:'2026-10-01',overdue:false},{id:'b',name:'عمر',status:'قيد التنفيذ',progress:10,due:'2026-10-01',overdue:true}]}]:[]};},storage:{from(){return {async upload(path,file){uploads.push({path,name:file.name});return {data:{path}}},async remove(){return {data:[]}}}}},functions:{async invoke(){return {data:{}}}}};
window.controller=createTaskBatchesController({getProfile:()=>profile,getSupabase:async()=>sb,onChanged:async()=>{refreshed++},toast:(...x)=>messages.push(x)});
</script></body></html>`;
const server=createServer((req,res)=>{if(req.url==='/'){res.setHeader('Content-Type','text/html');res.end(harness);return;}const path=resolve(root,'.'+req.url.split('?')[0]);if(!path.startsWith(root+'/')||!existsSync(path)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',path.endsWith('.css')?'text/css':'text/javascript');res.end(readFileSync(path));});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({executablePath:process.env.LAB_BROWSER||'/workspace/scratch/8fa5605f660d/browser-test/chrome-headless-shell-linux64/chrome-headless-shell',headless:true,args:['--no-sandbox']});
try{const page=await browser.newPage({viewport:{width:1280,height:950}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}/`);await page.waitForFunction(()=>window.controller);await page.click('#bulkAssignButton');await page.waitForSelector('#batchForm');await page.fill('#batchTitle','تحديث ملفات الموظفين');await page.selectOption('#batchDepartment','المبيعات');await page.click('#batchSelectDepartment');assert.match(await page.textContent('#batchCount'),/2/);await page.selectOption('#batchDepartment','');assert.equal(await page.locator('#batchPeople img').count(),0,'Names must be escaped');await page.setInputFiles('#batchFiles',{name:'instructions.txt',mimeType:'text/plain',buffer:Buffer.from('instructions')});await page.screenshot({path:'/tmp/bulk-desktop.png',fullPage:true});await page.click('#batchSubmit');await page.waitForFunction(()=>document.querySelector('#batchSubmit')?.textContent==='إعادة المحاولة');assert.equal(await page.locator('#batchTitle').isDisabled(),true);await page.click('#batchSubmit');await page.waitForSelector('.batch-report');const c=await page.evaluate(()=>({calls,uploads,refreshed}));const writes=c.calls.filter(x=>x.name==='create_task_batch_safe');assert.equal(writes.length,2);assert.deepEqual(writes[0].args,writes[1].args,'Ambiguous response must retry identical request');assert.equal(c.uploads.length,1,'Retry must not upload attachment twice');assert.equal(c.refreshed,1);const stats=await page.locator('.batch-stats div').allTextContents();assert.ok(stats.includes('1المتبقي'));assert.ok(stats.includes('1بانتظار الاعتماد'));assert.ok(stats.includes('1المتأخر'));await page.click('#batchClose');await page.setViewportSize({width:390,height:844});await page.click('#bulkAssignButton');await page.waitForSelector('#batchForm');assert.equal(await page.evaluate(()=>document.querySelector('dialog').scrollWidth<=document.querySelector('dialog').clientWidth),true,'Mobile dialog has no horizontal overflow');const start=await page.locator('#batchStart').boundingBox(),end=await page.locator('#batchDue').boundingBox();assert.ok(Math.abs(start.y-end.y)<2,'Dates stay on same row');await page.screenshot({path:'/tmp/bulk-mobile.png',fullPage:true});await page.evaluate(()=>{profile={uid:'employee',role:'employee'};controller.syncRole()});assert.equal(await page.locator('dialog').count(),0,'Auth switch clears private dialog');assert.equal(await page.locator('#bulkAssignButton').isVisible(),false);assert.equal(await page.locator('#batchFollowButton').isVisible(),false);assert.deepEqual(errors,[]);console.log('PASS: department selection, escaping, one upload, identical network retry, approval summary, mobile layout, role switch/privacy.');}finally{await browser.close();await new Promise(r=>server.close(r));}
