import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const html=readFileSync(new URL('../admin/maintenance.html',import.meta.url),'utf8');
const source=html.slice(html.indexOf('async function load(){'),html.indexOf("document.getElementById('refresh').onclick"));
const elements=new Map(),queries=[];
let forceError=false;
const sb={from(table){const calls=[];let columns='',options={};const query={select(c,o={}){columns=c;options=o;return this},is(...a){calls.push(['is',...a]);return this},in(...a){calls.push(['in',...a]);return this},gte(...a){calls.push(['gte',...a]);return this},order(){return this},limit(){return this},then(resolve){queries.push({table,calls});let result={data:[],error:null,count:0};if(table==='tasks')result.count=159;if(table==='email_notification_outbox')result=options.head?{data:null,error:null,count:36}:{data:Array.from({length:30},()=>({status:'sent'})),error:null};if(table==='app_error_logs')result={data:Array.from({length:30},()=>({})),error:null,count:40};if(forceError&&table==='tasks')result.error=new Error('query unavailable');return Promise.resolve(result).then(resolve)}};return query},rpc:async()=>({data:[],error:null})};
const ctx=vm.createContext({sb,Date,esc:x=>String(x??''),date:()=>'',document:{getElementById(id){if(!elements.has(id))elements.set(id,{});return elements.get(id)},querySelectorAll:()=>[]},window:{},lucide:{createIcons(){}}});
vm.runInContext(source,ctx);
await ctx.load();
assert.equal(elements.get('activeTasks').textContent,159);
assert.equal(elements.get('failedEmails').textContent,36,'Attention counter must include failures beyond the thirty displayed messages');
assert.equal(elements.get('recentErrors').textContent,40,'Errors counter must not be capped by the displayed rows');
const active=queries.find(q=>q.table==='tasks');
assert.ok(active.calls.some(c=>c[0]==='is'&&c[1]==='deleted_at'&&c[2]===null));
assert.ok(active.calls.some(c=>c[0]==='is'&&c[1]==='cancelled_at'&&c[2]===null));
assert.deepEqual(Array.from(active.calls.find(c=>c[0]==='in'&&c[1]==='status')[2]),['قيد الانتظار','قيد التنفيذ','بانتظار الاعتماد']);
forceError=true;
await assert.rejects(ctx.load(),/query unavailable/,'Query errors must not render zero counts as healthy');
console.log('Maintenance count behavior passed');
