import {readFileSync,writeFileSync} from 'node:fs';
import vm from 'node:vm';
const read=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8');
const nodes=new Map();const node=id=>{if(!nodes.has(id))nodes.set(id,{innerHTML:'',value:'',style:{},hidden:false,querySelector:node,querySelectorAll:()=>[],addEventListener(){}});return nodes.get(id)};
const jobSource=read('assets/js/job-library-page.js');
const jobs=[{id:'demo1',title:'منسق العمليات',job_code:'OPS-01',family:'العمليات',job_level:'أخصائي',status:'PUBLISHED',revision:2},{id:'demo2',title:'مشرف المشتريات',job_code:'PUR-01',family:'سلسلة الإمداد',job_level:'مشرف',status:'IN_REVIEW',revision:1},{id:'demo3',title:'محاسب أول',job_code:'FIN-01',family:'المالية',job_level:'أخصائي',status:'MANAGER_APPROVED',revision:1}];
const ctx=vm.createContext({jobs,el:node,canStage:()=>false,document:{querySelectorAll:()=>[]},window:{},location:{},console});
vm.runInContext(jobSource.slice(jobSource.indexOf('const esc='),jobSource.indexOf('let stagePermissions='))+jobSource.slice(jobSource.indexOf('function renderJobs()'),jobSource.indexOf('function renderAssignments()'))+'\nrenderJobs();',ctx);
let library=read('job-library/index.html').match(/<main class="atwar-content">([\s\S]*?)<\/main>/)[1];
for(const id of ['stats','grid'])library=library.replace(new RegExp(`(<div id="${id}"[^>]*>)[\\s\\S]*?<\\/div>`),`$1${node(id).innerHTML}</div>`);
library=library.replace(/<div id="state"[^>]*>[\s\S]*?<\/div>/,'');
const policySource=read('assets/js/policies-page.js');
const policies=[{id:'p1',title:'سياسة الإجازات',code:'HR-01'},{id:'p2',title:'سياسة الانتداب والنقل الوظيفي',code:'HR-02'},{id:'p3',title:'سياسة إدارة المشاريع',code:'PM-01'}];
const vs=[{policy_id:'p1',status:'APPROVED',version_number:2,effective_date:'2026-10-01'},{policy_id:'p2',status:'REVIEW',version_number:1},{policy_id:'p3',status:'RATIFICATION',version_number:1}];
const pc=vm.createContext({document:{getElementById:node},createForm(){},console,Date});
vm.runInContext(policySource.slice(0,policySource.indexOf('function createForm()')),pc);
pc.sbFixture={from(table){return {select(){return this},order(){return {data:table==='policies'?policies:vs,error:null}}}}};
await vm.runInContext("sb=sbFixture;profile={role:'admin'};list();",pc);
library=library.replaceAll('href="employee-changes.html"','href="../../job-library/employee-changes.html"');
const views={library,policies:`<div class="policy-wrap">${node('policyApp').innerHTML}</div>`};
views.policies=views.policies.replaceAll('href="?id=','href="../../policies/index.html?id=');
const html=`<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>معاينة المكتبات · بيانات تجريبية</title><link href="https://fonts.googleapis.com/css2?family=Tajawal:wght@400;500;700;800;900&display=swap" rel="stylesheet"><script src="https://unpkg.com/lucide@1.47.0"></script>${['design-system.css?v=2.5.8','shared.css?v=2.5.26','job-library.css','job-library-v2.css','policies.css?v=2.5.26','app-theme.css?v=2.5.34','typography.css?v=2.5.4.1'].map(p=>`<link rel="stylesheet" href="../../assets/css/${p}">`).join('')}<style>body{background:#f3f6fa}.preview-main{margin:0 auto!important;padding:24px;max-width:1320px;display:block!important}.preview-nav{display:flex;gap:8px;margin-bottom:20px}.preview-view[hidden]{display:none!important}</style></head><body><main class="atwar-main preview-main"><p>معاينة ببيانات تجريبية؛ لا تتصل ببيانات الشركة. الإجراءات معطلة.</p><nav class="preview-nav"><button class="atwar-btn" data-preview="library">مكتبة الوظائف</button><button class="atwar-btn" data-preview="policies">مكتبة السياسات</button></nav>${Object.entries(views).map(([id,html])=>`<section class="preview-view" id="${id}" ${id==='library'?'':'hidden'}>${html}</section>`).join('')}</main><script>window.lucide?.createIcons();document.querySelectorAll('[data-preview]').forEach(b=>b.onclick=()=>document.querySelectorAll('.preview-view').forEach(p=>p.hidden=p.id!==b.dataset.preview));document.querySelectorAll('button:not([data-preview]),input,select,textarea').forEach(x=>x.disabled=true);document.querySelectorAll('a,form').forEach(x=>x.addEventListener('click',e=>e.preventDefault()));</script></body></html>`;
writeFileSync(new URL('../tests/fixtures/libraries.html',import.meta.url),html);
console.log('Generated actual job and policy library markup with synthetic data.');
