import {readFileSync,writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import vm from 'node:vm';
import {escapeHTML} from '../assets/js/tasks-core.mjs';
import * as core from '../assets/js/projects-core.mjs';
export function renderProjectPreview(view){
 const nodes=new Map();const element=id=>{if(!nodes.has(id))nodes.set(id,{innerHTML:'',querySelector:element,querySelectorAll:()=>[],addEventListener(){},setAttribute(){},removeAttribute(){}});return nodes.get(id);};
 const source=readFileSync(new URL('../assets/js/projects-page.js',import.meta.url),'utf8').replace(/^import .*;\n/gm,'').split('try{sb=await window.atwarGetSupabase();')[0];
 const context={...core,esc:escapeHTML,document:{getElementById:element},innerWidth:1363,addEventListener(){},clearInterval(){},setInterval(){return 0},requestAnimationFrame(){},console,Date,URLSearchParams,location:{search:''}};vm.createContext(context);
 const project={id:'demo',title:'مشروع تجريبي · تشغيل مستودع جديد',objective:'تجهيز مستودع وتشغيله وفق خطة واضحة ومسؤوليات محددة.',deliverables:'مستودع مجهز، فريق مدرب، ومحضر تشغيل معتمد.',manager_id:'manager',sponsor_id:'sponsor',start_date:'2026-10-01',due_date:'2026-11-30',status:'ACTIVE',health:'ON_TRACK'};
 const people=[{id:'manager',full_name:'مدير المشروع'},{id:'sponsor',full_name:'المسؤول عن اعتماد المشروع'},{id:'member',full_name:'عضو الفريق'}];
 const tasks=[{id:'t1',title:'اعتماد الموقع والمخطط',project_phase_id:'p1',assignee_id:'member',assignee_name_snapshot:'عضو الفريق',start_date:'2026-10-01',due_date:'2026-10-10',progress:100,status:'مكتملة',project_weight:2},{id:'t2',title:'توريد التجهيزات',project_phase_id:'p2',assignee_id:'member',assignee_name_snapshot:'عضو الفريق',start_date:'2026-10-11',due_date:'2026-10-30',progress:45,status:'قيد التنفيذ',project_weight:3},{id:'t3',title:'التشغيل التجريبي',project_phase_id:'p2',assignee_id:'manager',assignee_name_snapshot:'مدير المشروع',start_date:'2026-11-01',due_date:'2026-11-20',progress:0,status:'قيد الانتظار',project_weight:2},{id:'t4',title:'اعتماد التشغيل',project_phase_id:'p2',assignee_id:'manager',assignee_name_snapshot:'مدير المشروع',start_date:'2026-11-30',due_date:'2026-11-30',progress:0,status:'قيد الانتظار',project_weight:1,project_milestone:true}];
 vm.runInContext(source+`\nme={id:'manager',role:'manager'};project=${JSON.stringify(project)};people=${JSON.stringify(people)};directory=people;tasks=${JSON.stringify(tasks)};phases=[{id:'p1',title:'التخطيط'},{id:'p2',title:'التجهيز والتشغيل'}];dependencies=[{task_id:'t2',predecessor_id:'t1'},{task_id:'t3',predecessor_id:'t2'},{task_id:'t4',predecessor_id:'t3'}];messages=[{id:'m1',author_id:'member',author_name:'عضو الفريق',created_at:'2026-10-01T10:00:00Z',body:'تم اعتماد المخطط، وننتظر تأكيد موعد التوريد.',mentions:['manager'],task_id:'t2'}];risks=[];files=[];events=[];tab=${JSON.stringify(view)};render();`,context);
 return nodes.get('projectApp').innerHTML.replace('<section class="project-box" id="projectPanel" role="tabpanel"></section>',`<section class="project-box" role="tabpanel">${nodes.get('#projectPanel').innerHTML}</section>`);
}
if(process.argv[1]===fileURLToPath(import.meta.url)){
 const views=['overview','gantt','list','board','chat','files','settings'];
 const html=`<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>معاينة إدارة المشاريع · بيانات تجريبية</title><link href="https://fonts.googleapis.com/css2?family=Tajawal:wght@400;500;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="../../assets/css/shared.css?v=2.5.26"><link rel="stylesheet" href="../../assets/css/projects.css?v=2.5.31"><link rel="stylesheet" href="../../assets/css/app-theme.css?v=2.5.27"><style>body{background:#f3f6fa;padding:24px;font-family:Tajawal,sans-serif}.preview-note{max-width:1440px;margin:0 auto 16px;color:#526277}#projectApp{display:block}.preview-page{display:grid;gap:16px}.preview-page[hidden]{display:none}</style></head><body><p class="preview-note">معاينة عامة ببيانات تجريبية — لا تتصل بحسابات أو بيانات الشركة. الحفظ والرفع والإجراءات معطلة.</p><main id="projectApp">${views.map(v=>`<div class="preview-page" data-view="${v}" ${v!=='gantt'?'hidden':''}>${renderProjectPreview(v).replaceAll('href="index.html"','href="../../projects/index.html"')}</div>`).join('')}</main><script>document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{const target=b.dataset.tab;document.querySelectorAll('[data-view]').forEach(p=>p.hidden=p.dataset.view!==target)});document.querySelectorAll('button:not([data-tab]),input,textarea,select').forEach(e=>e.disabled=true);document.querySelectorAll('form').forEach(f=>f.onsubmit=e=>e.preventDefault());document.querySelectorAll('a').forEach(a=>a.onclick=e=>e.preventDefault());</script></body></html>`;
 writeFileSync(new URL('../tests/fixtures/projects.html',import.meta.url),html);
}
