import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {createServer} from 'node:http';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';
const require=createRequire(import.meta.url);const {chromium}=require(require.resolve('playwright',{paths:[process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES]}));
const admin='797d5893-d44d-489c-9109-91da4882acfe',employee='eabb8105-e54d-45a3-90c8-15334698bbfc',manager='2347fbff-372e-43d1-a2e4-094f5b3159bf';let actor=employee;const source='00000000-0000-4000-8000-000000000001';
const db={profiles:[{id:admin,full_name:'مسؤول النظام',role:'admin',active:true,status:'active'},{id:employee,full_name:'موظف المبيعات',role:'employee',active:true,status:'active',manager_id:manager},{id:manager,full_name:'مدير المبيعات',role:'manager',active:true,status:'active'}],tasks:[{id:source,title:'اقتراح فرص لأتمتة إجراءات العمل',creator_id:admin,assignee_id:employee,status:'قيد التنفيذ',due_date:'2026-11-08',start_date:'2026-10-08',deleted_at:null}],projects:[],improvement_proposals:[],improvement_events:[],notifications:[],project_members:[]};
const server=createServer((req,res)=>{try{const path=resolve('.'+req.url.split('?')[0]);res.setHeader('content-type',path.endsWith('.mjs')||path.endsWith('.js')?'text/javascript':path.endsWith('.css')?'text/css':'text/html');res.end(readFileSync(path));}catch{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:'/workspace/scratch/8fa5605f660d/browser-test/chrome-headless-shell-linux64/chrome-headless-shell',headless:true,args:['--no-sandbox']});
try{const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://**/*',route=>route.fulfill({contentType:'text/javascript',body:'window.lucide={createIcons(){}};'}));
await page.route('**/assets/js/supabase-runtime.js*',route=>route.fulfill({contentType:'text/javascript',body:`const actor='${actor}';const session={user:{id:actor,email:'test@example.invalid'}};const sb={auth:{getSession:async()=>({data:{session}}),getUser:async()=>({data:{user:session.user}}),onAuthStateChange:()=>({data:{subscription:{unsubscribe(){}}}}),signOut:async()=>({})},from(table){let filters=[],single=false,limit=null,range=null;return {select(){return this},eq(k,v){filters.push(['eq',k,v]);return this},is(k,v){filters.push(['is',k,v]);return this},order(){return this},limit(n){limit=n;return this},range(a,b){range=[a,b];return this},single(){single=true;return this},maybeSingle(){single=true;return this},update(){return this},async then(resolve){const r=await fetch('/query',{method:'POST',body:JSON.stringify({table,filters,limit,range,single,actor})});return resolve(await r.json())}}},rpc:async(name,args)=>{const r=await fetch('/rpc',{method:'POST',body:JSON.stringify({name,args,actor})});return r.json()},channel:()=>({on(){return this},subscribe(){return this}}),removeChannel:async()=>{}};window.atwarGetSupabase=async()=>sb;window.ATWAR_SUPABASE=sb;`}));
await page.route('**/query',async route=>{const {table,filters,limit,range,single,actor}=route.request().postDataJSON();let data=db[table]||[];if(table==='improvement_proposals'&&actor!==admin)data=data.filter(x=>x.requester_id===actor);if(table==='tasks'&&actor!==admin)data=data.filter(x=>x.assignee_id===actor||x.creator_id===actor);if(table==='projects'&&actor!==admin)data=data.filter(x=>x.manager_id===actor||x.sponsor_id===actor);for(const [type,k,v] of filters)data=data.filter(x=>type==='is'?(x[k]??null)===v:x[k]===v);if(range)data=data.slice(range[0],range[1]+1);if(limit)data=data.slice(0,limit);await route.fulfill({contentType:'application/json',body:JSON.stringify({data:single?data[0]||null:data,error:null})});});
await page.route('**/rpc',async route=>{const {name,args,actor}=route.request().postDataJSON();let data=null,error=null;try{if(name==='communication_status')data=false;else if(name==='project_directory')data=db.profiles;else if(name==='improvement_execution'){const p=db.improvement_proposals.find(p=>p.id===args.p_id);data={kind:p.task_id?'task':'project',status:p.task_id?'قيد الانتظار':'PLANNING',progress:0,responsible:'مدير المبيعات',due_date:'2026-12-01'};}else if(name==='improvement_command'){const {p_action:action,p_data:input}=args;let p=db.improvement_proposals.find(x=>x.id===args.p_id);if(action==='submit'){p={...input,id:crypto.randomUUID(),requester_id:actor,requester_name:db.profiles.find(p=>p.id===actor).full_name,status:'SUBMITTED',revision:1,created_at:new Date().toISOString(),updated_at:new Date().toISOString()};db.improvement_proposals.push(p);}else{if(actor!==admin)throw Error('denied');if(p.revision!==args.p_revision)throw Error('ATWAR_CONFLICT');if(action==='decide'){p.status=input.status;p.decision_note=input.note;p.priority=input.priority||null;}else if(action==='task'){p.task_id=crypto.randomUUID();db.tasks.push({id:p.task_id,title:p.title,creator_id:actor,assignee_id:input.assignee_id,status:'قيد الانتظار',deleted_at:null});}else{p.project_id=crypto.randomUUID();db.projects.push({id:p.project_id,title:p.title,manager_id:input.manager_id,sponsor_id:input.sponsor_id,status:'PLANNING',deleted_at:null});}p.revision++;}db.improvement_events.push({id:crypto.randomUUID(),proposal_id:p.id,actor_name:'مستخدم الاختبار',action:action==='decide'?input.status:action,note:input.note||'إجراء',created_at:new Date().toISOString()});data=p.task_id||p.project_id||p.id;}}catch(e){error={message:e.message};}await route.fulfill({contentType:'application/json',body:JSON.stringify({data,error})});});
const url='http://127.0.0.1:'+server.address().port+'/workspace/improvements.html';await page.goto(url+'?task='+source);await page.waitForSelector('#proposalDialog[open]');assert.equal(await page.inputValue('[name=source_task_id]'),source);for(const [name,value] of Object.entries({title:'اختصار متابعة الطلبات <script>',current_process:'تجميع طلبات الفروع يدويًا',problem:'تكرار الاتصال لتحديث الحالات',benefit:'توفير الوقت وتقليل الأخطاء'}))await page.fill('#proposalForm [name='+name+']',value);
await page.locator('#proposalForm [type=submit]').click();await page.waitForSelector('.improvement-detail');assert.equal(await page.locator('#decisionForm').count(),0);assert.equal(db.improvement_proposals.length,1);assert.equal(await page.locator('.improvement-detail script').count(),0);const id=db.improvement_proposals[0].id;
actor=admin;await page.goto(url+'?id='+id);await page.waitForSelector('#decisionForm');await page.fill('#decisionForm [name=note]','ندرس الإمكانية والأثر');await page.click('#decisionForm [type=submit]');await page.waitForSelector('#decisionForm [name=status] option[value=ACCEPTED]',{state:'attached'});await page.selectOption('#decisionForm [name=status]','ACCEPTED');await page.selectOption('#decisionForm [name=priority]','HIGH');await page.fill('#decisionForm [name=note]','قابلة للتنفيذ وتوفر وقت الموظفين');await page.click('#decisionForm [type=submit]');await page.waitForSelector('#executionForm');
await page.fill('#executionForm [name=due_date]','2026-12-01');await page.selectOption('#executionForm [name=kind]','project');await page.selectOption('#executionForm [name=manager_id]',manager);await page.selectOption('#executionForm [name=sponsor_id]',admin);await page.click('#executionForm [type=submit]');await page.waitForSelector('#executionBox progress');assert.equal(db.projects.length,1);assert.equal(await page.locator('#executionForm').count(),0);
for(const width of [1440,390]){await page.setViewportSize({width,height:1000});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);await page.screenshot({path:'/tmp/improvement-admin-'+width+'.png',fullPage:true});}
actor=employee;await page.goto(url+'?id='+id);await page.waitForSelector('#executionBox progress');assert.equal(await page.locator('#executionBox a').count(),0,'Owner can follow summary without project access');assert.equal(await page.locator('#decisionForm').count(),0);await page.screenshot({path:'/tmp/improvement-employee-390.png',fullPage:true});
await page.goto(url);await page.waitForSelector('.improvement-card');await page.click('#addProposal');await page.screenshot({path:'/tmp/improvement-submit-390.png'});assert.deepEqual(errors,[]);console.log('PASS improvements real-script UI: employee source-linked submission, admin study/accept/project conversion, caller-scoped execution links, escaped text, desktop/mobile');
}finally{await browser.close();server.close();}
