document.body.classList.add('communication-page');
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const attachmentType=f=>{const map={docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',xlsx:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',pdf:'application/pdf',txt:'text/plain',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',webp:'image/webp'};const t=(f.type||'').toLowerCase();return ['', 'application/octet-stream','application/zip','application/x-zip-compressed'].includes(t)?map[f.name.split('.').pop().toLowerCase()]||t:t;};
const types={direct:'محادثة مباشرة',group:'مجموعة عمل',project:'مشروع',announcement:'إعلانات رسمية',task:'نقاش مهمة'};
let state=null,active=null,filter='all',reply=null,file=null,mentions=[],sourceMessage=null,events=null,busy=false,loading=false,loadAgain=false,detailTask=null,epoch=0;
const olderMessages=new Map(),historyEnded=new Set();
let historyLoading=false;
let notificationTarget=null,editingGroup=null,currentPage='communication',peopleMode=false,conversationView='chat',threadRoot=null,threadFile=null,notificationBaseline=null,notifying=false;
const sessionChannel=typeof BroadcastChannel!=='undefined'&&!window.COMMUNICATION_REVIEW?null:null;
const deviceId=sessionStorage.getItem('communication-device')||crypto.randomUUID();sessionStorage.setItem('communication-device',deviceId);let lastActivity=Date.now();
const statuses={available:'متاح',away:'بعيد',dnd:'عدم الإزعاج',offline:'غير متصل'};
const person=id=>state.users.find(x=>x.id===id),conv=()=>state?.conversations.find(x=>x.id===active),title=c=>c.type==='direct'?person(c.members.find(x=>x!==state.me.id))?.name||'محادثة مباشرة':c.title;
const time=iso=>new Intl.DateTimeFormat('ar-SA',{hour:'numeric',minute:'2-digit',timeZone:'Asia/Riyadh'}).format(new Date(iso));
const day=iso=>new Intl.DateTimeFormat('ar-SA-u-ca-gregory',{day:'numeric',month:'long',timeZone:'Asia/Riyadh'}).format(new Date(iso));
const notice=text=>{$('notice').textContent=text||'';};
const store=(key,data)=>localStorage.setItem('communication-production-'+key,JSON.stringify(data));
const load=(key,fallback)=>{try{return JSON.parse(localStorage.getItem('communication-production-'+key))??fallback;}catch{return fallback;}};
const currentDraftKey=()=>threadRoot?`thread-draft-${state.me.id}-${threadRoot}`:draftKey();
const queue=()=>load('outbox-'+state.me.id,[]),draftKey=()=>`draft-${state.me.id}-${active}`;
$('newChat').disabled=true;
const sb=await window.atwarGetSupabase();
const initialIdentity=(await sb.auth.getUser()).data?.user?.id;
sb.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'||(event==='SIGNED_IN'&&initialIdentity&&session?.user?.id!==initialIdentity)){epoch++;events?.close();state=null;active=null;olderMessages.clear();historyEnded.clear();document.querySelector('.lab-shell')?.replaceChildren();$('toastArea')?.replaceChildren();document.querySelectorAll('dialog').forEach(d=>{d.close();d.replaceChildren();});location.href='../login.html';}});
async function api(path,data){
 if(path==='session')throw new Error('تغيير الحساب متاح من تسجيل الدخول إلى النظام فقط.');
 const {data:result,error}=await sb.functions.invoke('communication',{body:{path,data}});
 if(error){let body;try{body=await error.context?.json();}catch{}const e=new Error(body?.error||error.message);e.status=error.context?.status;throw e;}return result;
}

async function act(action,data){const result=await api('action',{action,data});await sync();return result;}
function status(online){$('connection').textContent=innerWidth<=700?(online?'متصل':'غير متصل'):(online?'متصل · تحديث فوري':'غير متصل · الرسائل محفوظة للإرسال');$('connection').classList.toggle('offline',!online);}
function unread(c){return state.messages.filter(m=>m.conversation===c.id&&m.sender!==state.me.id&&m.seq>(m.thread?(state.threadReads?.[m.thread]||0):(state.reads[c.id]||0))).length;}
function avatar(id,type){const p=person(id),paths={group:'<circle cx="9" cy="8" r="3"/><path d="M3 20v-2a6 6 0 0 1 12 0v2M16 5a3 3 0 0 1 0 6M18 15a5 5 0 0 1 3 5"/>',project:'<path d="M4 4v16h16M8 7h7M11 12h9M7 17h6"/>',announcement:'<path d="m4 10 14-5v14L4 14zM4 10H2v4h2M7 15l2 6h3l-2-5"/>',task:'<rect x="3" y="3" width="18" height="18" rx="3"/><path d="m7 12 3 3 7-7"/>'};return `<span class="avatar ${type?'avatar-'+type:''}">${paths[type]?`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true">${paths[type]}</svg>`:esc(p?.name?.slice(0,1)||'•')}${p?.status&&p.status!=='offline'?`<span class="online-dot ${p.status}"></span>`:''}</span>`;}

function renderList(){
 const q=$('search').value.trim().toLowerCase();const rows=state.conversations.filter(c=>{
  const ms=state.messages.filter(m=>m.conversation===c.id);return (!q||title(c).toLowerCase().includes(q)||ms.some(m=>m.body.toLowerCase().includes(q)))&&(filter==='all'||filter==='unread'&&unread(c)||filter==='mentions'&&ms.some(m=>m.mentions.includes(state.me.id))||filter==='saved'&&ms.some(m=>state.saved.includes(m.id)));
 }).sort((a,b)=>Number(state.favorites.includes(b.id))-Number(state.favorites.includes(a.id))||Math.max(0,...state.messages.filter(m=>m.conversation===b.id).map(m=>m.seq))-Math.max(0,...state.messages.filter(m=>m.conversation===a.id).map(m=>m.seq)));
 let previous='';$('conversations').innerHTML=rows.map(c=>{const fav=state.favorites.includes(c.id),section=fav?'المفضلة':'الأحدث';const label=previous!==section?`<div class="section-label">${section}</div>`:'';previous=section;const last=state.messages.filter(m=>m.conversation===c.id).at(-1),count=unread(c);return label+`<button class="conversation ${active===c.id?'selected':''}" data-conversation="${c.id}">${avatar(c.type==='direct'?c.members.find(x=>x!==state.me.id):null,c.type)}<span class="conversation-copy"><strong>${esc(title(c))}</strong><small>${esc(last?.body||last?.file?.name||types[c.type])}</small></span><span class="conversation-tail">${last?`<time>${time(last.created)}</time>`:''}${count?`<span class="badge">${count}</span>`:''}</span></button>`;}).join('')||'<div class="empty">لا توجد محادثات مطابقة.</div>';
 if(filter==='all'&&state.projects?.length)$('conversations').innerHTML+='<div class="section-label">نقاشات المشاريع</div>'+state.projects.filter(p=>!q||p.title.toLowerCase().includes(q)).map(p=>`<a class="conversation" href="../projects/index.html?id=${encodeURIComponent(p.id)}&view=chat">${avatar(null,'project')}<span class="conversation-copy"><strong>${esc(p.title)}</strong><small>فتح نقاش المشروع في سجله المعتمد</small></span></a>`).join('');
}
function renderHead(){const c=conv();if(!c){$('chatHead').innerHTML='';$('composer').hidden=true;return;}const others=c.members.filter(x=>x!==state.me.id),online=others.filter(x=>person(x)?.online).length;
 $('chatHead').innerHTML=`<button class="icon mobile-back" id="back" aria-label="قائمة المحادثات">›</button>${avatar(c.type==='direct'?others[0]:null,c.type)}<div class="chat-heading"><h2 title="${esc(title(c))}">${esc(title(c))}</h2><small>${types[c.type]} · ${c.type==='direct'?(statuses[person(others[0])?.status]||'غير متصل'):c.members.length+' أعضاء · '+online+' متصل'}</small></div><button id="favorite" aria-label="${state.favorites.includes(c.id)?'إلغاء التفضيل':'إضافة للمفضلة'}">${state.favorites.includes(c.id)?'★':'☆'}</button><button id="mute">${state.muted.includes(c.id)?'إلغاء الكتم':'كتم'}</button><button id="showDetails">التفاصيل</button>${!historyEnded.has(c.id)&&state.messages.filter(m=>m.conversation===c.id).length>=300?'<button data-older-messages>رسائل أقدم</button>':''}<nav class="conversation-tabs" aria-label="محتوى المحادثة"><button data-view="chat" aria-selected="${conversationView==='chat'}">المحادثة</button><button data-view="files" aria-selected="${conversationView==='files'}">الملفات</button></nav>`;
 const writable=c.type!=='announcement'||state.me.role==='admin';$('send').disabled=!$('messageInput').value.trim()&&!file;$('composer').hidden=!writable||conversationView==='files';$('messages').hidden=conversationView==='files';$('conversationFiles').hidden=conversationView!=='files';renderFiles();$('replyBar').hidden=!reply||conversationView==='files';$('attachmentBar').hidden=!file||conversationView==='files';
 if(!writable)notice('النشر في الإعلانات متاح لمسؤول النظام. القراءة ليست موافقة أو إقرارًا رسميًا.');else if($('notice').textContent.includes('النشر في الإعلانات'))notice('');
}
function messageHTML(m,threadMode=false){const original=m.reply?state.messages.find(x=>x.id===m.reply):null;
  const task=m.task?`<button class="task-card" data-task="${m.task.id}" ${m.task.real?'data-real-task="true"':''} ${m.task.restricted?'disabled':''}>${m.task.restricted?'مهمة بصلاحية محددة':`▣ ${esc(m.task.title)}<small>${esc(m.task.status)} · ${esc(person(m.task.assignee)?.name)} · ${esc(m.task.due)}</small>`}</button>`:'';
  return `<article class="message ${m.id===notificationTarget?'message-target':''} ${m.sender===state.me.id?'mine':''} ${m.mentions.includes(state.me.id)?'mentioned':''} ${m.pending?'pending':''}" data-message="${m.id}">${avatar(m.sender)}<div class="message-content">${m.pinned?'<div class="pinned">مثبتة في المحادثة</div>':''}<div class="message-meta"><strong>${esc(person(m.sender)?.name)}</strong><time>${time(m.created)}</time>${m.pending?'<span class="saving">بانتظار الاتصال</span>':''}</div>${original&&!threadMode?`<div class="quote">رد على ${esc(person(original.sender)?.name)}: ${esc(original.body.slice(0,160))}</div>`:''}${m.body?`<p class="message-body">${esc(m.body)}</p>`:''}${m.file?`<a class="file" href="#" data-trial-file="${m.file.id}" download="${esc(m.file.name)}">↧ ${esc(m.file.name)} · ${Math.ceil(m.file.size/1024)} كيلوبايت</a>`:''}${task}${!threadMode?threadLink(m):''}${m.pending?'':`<div class="message-actions"><button data-action="reply" data-id="${m.id}">رد</button><button data-action="react" data-id="${m.id}" class="${m.reactions.includes(state.me.id)?'active':''}">تفاعل ${m.reactions.length||''}</button><button data-action="save" data-id="${m.id}" class="${state.saved.includes(m.id)?'active':''}">${state.saved.includes(m.id)?'محفوظة':'للمتابعة'}</button><details class="message-more"><summary aria-label="المزيد من إجراءات الرسالة">المزيد ···</summary><div class="message-menu">${conv().type==='direct'||conv().owner===state.me.id||state.me.role==='admin'?`<button data-action="pin" data-id="${m.id}">${m.pinned?'إلغاء التثبيت':'تثبيت'}</button>`:''}${!m.task?`<button data-action="createTask" data-id="${m.id}">إنشاء مهمة</button><button data-action="linkTask" data-id="${m.id}">ربط بمهمة</button>`:''}</div></details></div>`}</div></article>`;
}
function threadLink(m){const root=m.thread||m.id;const rows=state.messages.filter(x=>x.thread===root);const count=rows.filter(x=>x.sender!==state.me.id&&x.seq>(state.threadReads?.[root]||0)).length;return rows.length||m.thread?`<button class="thread-link" data-thread="${root}">${m.thread?'فتح النقاش':rows.length+' ردود'}${count?`<span class="unread-thread">${count}</span>`:''}</button>`:'';}
function renderMessages(forceBottom=false){
 if(!conv()){ $('messages').innerHTML='<div class="empty"><b>ابدأ محادثة جديدة</b>اختر زميلًا من قائمة الموظفين أو أنشئ مجموعة عمل.</div>';return;}const host=$('messages'),previousLast=host.dataset.lastMessage,near=host.scrollHeight-host.scrollTop-host.clientHeight<90,top=host.scrollTop;
 const q=$('search').value.trim().toLowerCase();let messages=state.messages.filter(m=>m.conversation===active&&(!m.thread||filter==='saved'||filter==='mentions'||q));
 if(filter==='saved')messages=messages.filter(m=>state.saved.includes(m.id));if(filter==='mentions')messages=messages.filter(m=>m.mentions.includes(state.me.id));if(q)messages=messages.filter(m=>m.body.toLowerCase().includes(q)||title(conv()).toLowerCase().includes(q));
 const pending=queue().filter(m=>m.conversation===active&&!m.reply).map(m=>({...m,id:m.clientId,sender:state.me.id,created:m.created,reactions:[],pending:true}));messages=[...messages,...pending];const signature=JSON.stringify([state.me.id,active,filter,q,notificationTarget,state.seq,state.saved,state.threadReads,state.messages.map(m=>[m.id,m.reactions,m.pinned,m.task]),pending]);if(host.dataset.signature===signature){if(forceBottom){host.scrollTop=host.scrollHeight;$('newMessages').hidden=true;}if(forceBottom||near)markRead();return;}host.dataset.signature=signature;const latestId=messages.at(-1)?.clientId||messages.at(-1)?.id||'';host.dataset.lastMessage=latestId;let date='';
 host.innerHTML=messages.map(m=>{
  const d=day(m.created),separator=date!==d?`<div class="day-separator">${d}</div>`:'';date=d;const original=m.reply?state.messages.find(x=>x.id===m.reply):null;
  return separator+messageHTML(m);
 }).join('')||'<div class="empty"><b>ابدأ الحديث</b>شارك فكرة أو ملفًا، واجعل النقاش قريبًا من العمل.</div>';
 if(forceBottom||near){host.scrollTop=host.scrollHeight;$('newMessages').hidden=true;markRead();}else{host.scrollTop=top;if(previousLast!==latestId&&latestId)$('newMessages').hidden=false;}
}
let readBusy=false;
async function markRead(){if(!state||!active||currentPage!=='communication'||conversationView!=='chat'||$('threadDialog').open||document.hidden||(innerWidth<=700&&!$('layout').classList.contains('chat-open'))||filter!=='all'||$('search').value||readBusy)return;const latest=Math.max(0,...state.messages.filter(m=>m.conversation===active&&!m.thread).map(m=>m.seq));if((state.reads[active]||0)>=latest)return;const cid=active,reader=state.me.id;readBusy=true;try{await api('action',{action:'read',data:{conversation:cid,seq:latest}});if(state?.me.id===reader){state.reads[cid]=latest;renderList();renderNotifications();heartbeat();}}catch{}finally{readBusy=false;}}
function renderDetails(){if($('details').hidden||!conv())return;const c=conv(),task=detailTask?state.tasks.find(x=>x.id===detailTask):null;
 $('details').innerHTML=`<div class="detail-head"><h3>${task?'تفاصيل المهمة':'تفاصيل المحادثة'}</h3><button id="closeDetails" class="icon" aria-label="إغلاق التفاصيل">×</button></div>${task?`<h3>${esc(task.title)}</h3><p class="hint">${esc(task.status)} · ${esc(task.due)}</p><p class="hint">المسند إليه: ${esc(person(task.assignee)?.name)}</p><button class="primary link-source" data-conversation="${task.conversation}">فتح نقاش المهمة</button>${state.conversations.some(x=>x.id===task.sourceConversation)?`<button class="link-source" data-conversation="${task.sourceConversation}">المحادثة الأصلية</button>`:''}<p class="hint">الحالات والاعتمادات الرسمية ستُربط بمحرك المهام بعد اعتماد التجربة. لا تغيّر هذه النسخة مهام النظام.</p>`:`<p class="hint">${types[c.type]} · ${c.members.length} أعضاء</p>${c.type==='group'&&(c.owner===state.me.id||state.me.role==='admin')?'<button id="manageMembers">إدارة الأعضاء</button>':''}<h4>فريق المحادثة</h4>${c.members.map(id=>`<div class="person">${avatar(id)}<div><strong>${esc(person(id)?.name)}</strong><small>${esc(person(id)?.department)} · ${statuses[person(id)?.status]||'غير متصل'}</small></div></div>`).join('')}<div class="detail-section"><h4>الملفات</h4>${state.messages.filter(m=>m.conversation===active&&m.file).map(m=>`<a class="file" href="#" data-trial-file="${m.file.id}" download>${esc(m.file.name)}</a>`).join('')||'<p class="hint">لا توجد ملفات بعد.</p>'}</div><div class="detail-section"><h4>الرسائل المثبتة</h4>${state.messages.filter(m=>m.conversation===active&&m.pinned).map(m=>`<p class="hint">${esc(m.body)}</p>`).join('')||'<p class="hint">لا توجد رسائل مثبتة.</p>'}</div>`}`;
}
function selectConversation(id,openChat=true){
 if(state&&active)store(draftKey(),$('messageInput').value);if(currentPage!=='communication')navigatePage('communication');closeThread();notificationTarget=null;conversationView='chat';active=id;reply=null;file=null;mentions=[];detailTask=null;$('layout').classList.toggle('chat-open',openChat);$('messageInput').value=load(draftKey(),'');renderList();renderHead();renderMessages(true);renderDetails();if(innerWidth>700)$('messageInput').focus();heartbeat();
}
async function sync(){if(loading){loadAgain=true;return;}loading=true;const version=epoch;try{
 const next=await api('state',{target:new URLSearchParams(location.search).get('message')});if(version!==epoch)return;for(const [id,rows] of olderMessages){if(!next.conversations.some(c=>c.id===id)){olderMessages.delete(id);continue;}const known=new Set(next.messages.map(m=>m.id));next.messages.unshift(...rows.filter(m=>!known.has(m.id)));}next.messages.sort((a,b)=>a.seq-b.seq);
 state=next;$('newChat').disabled=false;const requested=new URLSearchParams(location.search);if(requested.has('conversation')&&state.conversations.some(c=>c.id===requested.get('conversation'))){active=requested.get('conversation');notificationTarget=requested.get('message');history.replaceState(null,'',location.pathname);}try{store('state-'+state.me.id,state);store('current',state.me.id);}catch{notice('المساحة المحلية ممتلئة؛ عرض الرسائل متاح، لكن حفظ نسخة دون اتصال غير متاح.');}status(true);$('identity').textContent=state.me.name;
 if(!active||!state.conversations.some(c=>c.id===active))active=state.conversations.find(c=>c.type==='direct')?.id||state.conversations[0]?.id;
 renderList();renderHead();renderMessages();renderDetails();renderPeople();renderWorkPage();renderThread();renderNotifications();updateIdentity();processNotifications();
 }catch(e){status(false);if(e.status===401||e.status===403){epoch++;state=null;active=null;olderMessages.clear();historyEnded.clear();events?.close();for(const id of ['messages','conversationFiles','conversations','details','peopleList','notificationList','toastArea','threadMessages'])$(id).replaceChildren();$('composer').hidden=true;notice(e.message);}}finally{loading=false;if(loadAgain){loadAgain=false;sync();}}
}
function connect(){events?.close();const ch=sb.channel('communication-'+state.me.id).on('postgres_changes',{event:'*',schema:'public',table:'communication_revisions',filter:'user_id=eq.'+state.me.id},()=>sync()).subscribe(s=>{if(s==='SUBSCRIBED'){status(true);sync();flush();}else if(['CHANNEL_ERROR','TIMED_OUT','CLOSED'].includes(s))status(false);});events={close:()=>sb.removeChannel(ch)};}

async function switchAccount(id){if(!navigator.onLine){notice('تبديل الحساب يحتاج اتصالًا بالخادم التجريبي.');$('account').value=state?.me.id||'';return;}try{
 if(state&&active)store(draftKey(),$('messageInput').value);epoch++;closeThread();notificationBaseline=null;$('toastArea').replaceChildren();events?.close();await api('session',{user:id});sessionChannel?.postMessage('changed');while(loading)await new Promise(r=>setTimeout(r,20));$('layout').classList.remove('chat-open');state=null;active=null;reply=null;file=null;mentions=[];sourceMessage=null;detailTask=null;for(const id of ['messages','conversationFiles','details','conversations','mentionChoices','linkChoices','memberChoices'])$(id).replaceChildren();for(const id of ['newDialog','taskDialog','mentionDialog','linkDialog','notificationsDialog','settingsDialog'])$(id).close();$('taskTitle').value='';$('taskAssignee').replaceChildren();$('messageInput').value='';$('details').hidden=true;$('layout').classList.remove('with-details');await sync();$('account').value=id;const target=notificationTarget;selectConversation(active,innerWidth>700);if(target){const message=state.messages.find(m=>m.id===target);if(message?.thread)openThread(message.thread);notificationTarget=target;renderMessages();document.querySelector('[data-message="'+CSS.escape(target)+'"]')?.scrollIntoView({block:'center'});}heartbeat();connect();
 }catch(e){notice(e.message);}}
async function flush(){if(busy||!state||!navigator.onLine)return;busy=true;const who=state.me.id;try{
 for(const m of load('outbox-'+who,[])){
  if(state.me.id!==who)break;
  try{await api('action',{action:'message',data:m});const remaining=load('outbox-'+who,[]).filter(x=>x.clientId!==m.clientId);store('outbox-'+who,remaining);}catch(e){if(e.status){notice('تعذر إرسال رسالة محفوظة: '+e.message);break;}status(false);break;}
 }
 await sync();
 }finally{busy=false;}}
$('composer').onsubmit=async e=>{e.preventDefault();if(!conv()){ $('messages').innerHTML='<div class="empty"><b>ابدأ محادثة جديدة</b>اختر زميلًا من قائمة الموظفين أو أنشئ مجموعة عمل.</div>';return;}const body=$('messageInput').value.trim();if(!body&&!file)return;
 const m={conversation:active,body,file,reply,mentions:conv().members.filter(id=>id!==state.me.id&&body.includes('@'+person(id).name)),clientId:crypto.randomUUID(),created:new Date().toISOString()};
 if(file){if(!navigator.onLine){notice('رفع المرفقات يحتاج اتصالًا. بقي الملف والنص حتى إعادة الاتصال.');return;}if(busy)return;busy=true;$('send').disabled=true;notice('جارٍ رفع المرفق…');try{await api('action',{action:'message',data:m});$('messageInput').value='';store(draftKey(),'');reply=null;file=null;mentions=[];notice('');await sync();renderHead();renderMessages(true);}catch(err){notice('لم يُرسل المرفق: '+err.message);$('send').disabled=false;}finally{busy=false;}return;}
 try{store('outbox-'+state.me.id,[...queue(),m]);}catch{notice('تعذر حفظ الرسالة محليًا. لم تُرسل؛ جرّب ملفًا أصغر.');return;}
 $('messageInput').value='';store(draftKey(),'');reply=null;file=null;mentions=[];renderHead();renderMessages(true);notice('');await flush();};
$('messageInput').addEventListener('input',()=>{$('send').disabled=!$('messageInput').value.trim()&&!file;if(state&&active){try{store(draftKey(),$('messageInput').value);}catch{notice('تعذر حفظ المسودة على هذا الجهاز.');}}});
$('messageInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();$('composer').requestSubmit();}});
$('search').oninput=()=>{renderList();renderMessages();};
$('newMessages').onclick=()=>{$('messages').scrollTop=$('messages').scrollHeight;$('newMessages').hidden=true;markRead();};
$('messages').onscroll=()=>{if($('messages').scrollHeight-$('messages').scrollTop-$('messages').clientHeight<60){$('newMessages').hidden=true;markRead();}};
$('attach').onclick=()=>$('fileInput').click();
$('fileInput').onchange=async()=>{const f=$('fileInput').files[0];if(!f)return;if(f.size>10*1024*1024){notice('حد الملف ١٠ ميجابايت في التجربة.');return;}const base64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(f);});file={name:f.name,type:attachmentType(f),base64};$('attachmentBar').innerHTML=`<span>مرفق: ${esc(f.name)}</span><button id="cancelFile" class="icon" type="button">×</button>`;$('attachmentBar').hidden=false;$('send').disabled=false;$('fileInput').value='';};
$('mention').onclick=()=>{$('mentionChoices').innerHTML=conv().members.filter(id=>id!==state.me.id).map(id=>`<button class="choice" data-mention="${id}">${esc(person(id).name)}</button>`).join('');$('mentionDialog').showModal();};
$('newChat').onclick=()=>{editingGroup=null;$('chatType').value='direct';$('groupNameField').hidden=true;$('chatType').disabled=false;document.querySelector('#newDialog h2').textContent='محادثة جديدة';document.querySelector('#newForm .primary').textContent='فتح المحادثة';$('memberChoices').innerHTML='<legend>اختر المشاركين</legend>'+state.users.filter(p=>p.id!==state.me.id).map(p=>`<label><input type="checkbox" name="member" value="${p.id}">${esc(p.name)}</label>`).join('');$('newError').textContent='';$('groupName').value='';$('newDialog').showModal();};
$('chatType').onchange=()=>{$('groupNameField').hidden=$('chatType').value!=='group';};
$('newForm').onsubmit=async e=>{e.preventDefault();try{const members=[...document.querySelectorAll('[name="member"]:checked')].map(x=>x.value);const c=editingGroup?await act('updateMembers',{conversation:editingGroup,members}):await act('createConversation',{type:$('chatType').value,title:$('groupName').value,members});$('newDialog').close();selectConversation(c.id);}catch(e){$('newError').textContent=e.message;}};
$('taskForm').onsubmit=async e=>{e.preventDefault();try{const m=state.messages.find(x=>x.id===sourceMessage);const task=await act('createTask',{conversation:m.conversation,message:m.id,title:$('taskTitle').value,assignee:$('taskAssignee').value,due:$('taskDue').value});$('taskDialog').close();notice('تم إنشاء المهمة في النظام.');}catch(e){$('taskError').textContent=e.message;}};
$('account').onchange=()=>switchAccount($('account').value);
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{
 if(b.dataset.close){if(b.dataset.close==='threadDialog')closeThread();else $(b.dataset.close).close();return;}
 if(b.hasAttribute('data-older-messages')){if(historyLoading)return;historyLoading=true;const id=active,who=state.me.id,before=Math.min(...state.messages.filter(m=>m.conversation===id).map(m=>m.seq));try{const rows=await api('history',{conversation:id,before});if(state?.me.id!==who)return;olderMessages.set(id,[...(olderMessages.get(id)||[]),...rows]);if(rows.length<300)historyEnded.add(id);await sync();notice(rows.length?'تم تحميل الرسائل الأقدم.':'وصلت إلى بداية المحادثة.');}catch(err){notice(err.message);}finally{historyLoading=false;}return;}
 if(b.dataset.thread){if(!state.messages.some(m=>m.id===b.dataset.thread)){try{const row=await api('message',{id:b.dataset.thread});olderMessages.set(row.conversation,[...(olderMessages.get(row.conversation)||[]),row]);await sync();}catch(err){notice(err.message);return;}}openThread(b.dataset.thread);return;}
 if(b.dataset.colleague){const c=await act('createConversation',{type:'direct',members:[b.dataset.colleague]});selectConversation(c.id);return;}
 if(b.dataset.page){navigatePage(b.dataset.page);return;}
 if(b.dataset.notification){await openNotification(b.dataset.notification);return;}
 if(b.dataset.toastClose){b.closest('.message-toast').remove();return;}
 if(b.dataset.workDiscussion){selectConversation(b.dataset.workDiscussion);return;}
 if(b.dataset.view){conversationView=b.dataset.view;renderHead();if(conversationView==='chat')renderMessages(true);else $('newMessages').hidden=true;heartbeat();return;}
 if(b.dataset.conversation){selectConversation(b.dataset.conversation);return;}
 if(b.dataset.filter){filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('selected',x===b));renderList();renderMessages(true);return;}
 if(b.dataset.mention){const id=b.dataset.mention;if(!mentions.includes(id))mentions.push(id);$('messageInput').value+='@'+person(id).name+' ';$('send').disabled=false;$('mentionDialog').close();$('messageInput').focus();return;}
 if(b.dataset.task){const real=state.tasks.find(t=>t.id===b.dataset.task);if(real?.real||b.dataset.realTask){location.href='../tasks/index.html?task='+encodeURIComponent(b.dataset.task);return;}detailTask=b.dataset.task;$('details').hidden=false;$('layout').classList.add('with-details');renderDetails();return;}
 if(b.dataset.link){const m=state.messages.find(x=>x.id===sourceMessage);await act('linkTask',{conversation:m.conversation,message:m.id,task:b.dataset.link});$('linkDialog').close();return;}
 if(b.dataset.action){b.closest('details')?.removeAttribute('open');const m=state.messages.find(x=>x.id===b.dataset.id);if(b.dataset.action==='reply'){openThread(m.thread||m.id);return;}
  if(b.dataset.action==='createTask'){sourceMessage=m.id;$('taskTitle').value=m.body.slice(0,180);$('taskAssignee').innerHTML='<option value="">اختر الموظف</option>'+state.users.filter(p=>state.assignees?.includes(p.id)).map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');$('taskDue').value='';$('taskError').textContent='';$('taskDialog').showModal();return;}
  if(b.dataset.action==='linkTask'){sourceMessage=m.id;$('linkChoices').innerHTML=state.tasks.map(t=>`<button class="choice" data-link="${t.id}">${esc(t.title)} · ${esc(t.status)}</button>`).join('')||'<p class="hint">لا توجد مهام متاحة للربط.</p>';$('linkDialog').showModal();return;}
  await act(b.dataset.action,{conversation:m.conversation,message:m.id});return;
 }
 if(b.id==='manageMembers'){const c=conv();editingGroup=c.id;$('chatType').value='group';$('chatType').disabled=true;$('groupNameField').hidden=true;document.querySelector('#newDialog h2').textContent='إدارة أعضاء المجموعة';document.querySelector('#newForm .primary').textContent='حفظ الأعضاء';$('memberChoices').innerHTML='<legend>أعضاء المجموعة</legend>'+state.users.map(p=>`<label><input type="checkbox" name="member" value="${p.id}" ${c.members.includes(p.id)?'checked':''} ${p.id===c.owner?'disabled':''}>${esc(p.name)}${p.id===c.owner?' · مسؤول المجموعة':''}</label>`).join('');$('newError').textContent='';$('newDialog').showModal();return;}
 if(b.id==='favorite'||b.id==='mute')await act(b.id,{conversation:active});
 if(b.id==='showDetails'){detailTask=null;$('details').hidden=!$('details').hidden;$('layout').classList.toggle('with-details',!$('details').hidden);renderDetails();}
 if(b.id==='closeDetails'){$('details').hidden=true;$('layout').classList.remove('with-details');}
 if(b.id==='cancelReply'){reply=null;$('replyBar').hidden=true;}
 if(b.id==='cancelFile'){file=null;$('attachmentBar').hidden=true;$('send').disabled=!$('messageInput').value.trim();}
 if(b.id==='back'){$('layout').classList.remove('chat-open');heartbeat();}
 }catch(e){notice(e.message);}});
window.addEventListener('online',()=>{sync();flush();});window.addEventListener('offline',()=>status(false));
document.addEventListener('visibilitychange',()=>{heartbeat();if(!document.hidden){sync();if($('messages').scrollHeight-$('messages').scrollTop-$('messages').clientHeight<60)markRead();}});
setInterval(()=>{if(state&&navigator.onLine){heartbeat();sync();flush();}},20000);
function viewingConversation(){return state&&currentPage==='communication'&&conversationView==='chat'&&filter==='all'&&!$('search').value&&!document.hidden&&$('layout').classList.contains('chat-open')&&($('threadDialog').open||$('messages').scrollHeight-$('messages').scrollTop-$('messages').clientHeight<90)?active:null;}
let presenceChain=Promise.resolve();
function heartbeat(){if(!state||!navigator.onLine)return Promise.resolve();const who=state.me.id,version=epoch,payload={device:deviceId,active:lastActivity,viewing:viewingConversation(),thread:$('threadDialog').open?threadRoot:null};presenceChain=presenceChain.catch(()=>{}).then(async()=>{if(state?.me.id!==who||epoch!==version)return;try{await api('action',{action:'presence',data:payload});}catch{}});return presenceChain;}

function updateIdentity(){if(!state)return;$('selfAvatar').textContent=state.me.name.slice(0,1);$('selfStatus').textContent=statuses[person(state.me.id)?.status]||'غير متصل';$('availability').value=state.users.find(x=>x.id===state.me.id)?.status==='dnd'?'dnd':'auto';}
function renderPeople(){if(!state)return;const search=$('peopleSearch').value.trim().toLowerCase(),kind=$('peopleFilter').value;const rows=state.users.filter(p=>p.id!==state.me.id&&(!search||(p.name+' '+p.department).toLowerCase().includes(search))&&(kind==='all'||p.status===kind)).sort((a,b)=>({available:0,away:1,dnd:2,offline:3}[a.status]-{available:0,away:1,dnd:2,offline:3}[b.status])||a.name.localeCompare(b.name,'ar'));
 $('peopleList').innerHTML=rows.map(p=>`<button class="colleague" data-colleague="${p.id}">${avatar(p.id)}<span class="colleague-copy"><strong>${esc(p.name)}</strong><small>${esc(p.department)}</small><span class="presence-pill ${p.status}">${statuses[p.status]}</span></span></button>`).join('')||'<div class="empty">لا يوجد زملاء مطابقون.</div>';
}
function setPeopleMode(value){peopleMode=value;$('peopleSide').hidden=!value;$('conversationSide').hidden=value;$('peopleTab').setAttribute('aria-selected',String(value));$('conversationsTab').setAttribute('aria-selected',String(!value));renderPeople();}
const pageTitles={communication:['التواصل','محادثاتك وزملاؤك ونقاشات العمل في مكان واحد'],home:['الرئيسية','نظرة على أعمالك ورسائلك'],tasks:['المهام','المهام المتاحة لك ونقاشاتها المرتبطة'],projects:['إدارة المشاريع','المشروع ونقاشه من مساحة عمل واحدة']};
function navigatePage(page){if(!pageTitles[page])return;if(page!=='communication'){location.href=page==='home'?'../home.html':'../'+page+'/index.html';return;}if(threadRoot)closeThread();currentPage=page;document.body.classList.toggle('communication-page',page==='communication');$('layout').hidden=page!=='communication';$('workPage').hidden=page==='communication';$('pageTitle').textContent=pageTitles[page][0];$('pageSubtitle').textContent=pageTitles[page][1];document.querySelectorAll('[data-page]').forEach(e=>e.classList.toggle('active',e.dataset.page===page));renderWorkPage();heartbeat();if(page==='communication'){renderMessages();renderPeople();}}
function renderWorkPage(){if(!state||currentPage==='communication')return;
 if(currentPage==='home'){$('workPage').innerHTML=`<div class="home-review-note">هذه صفحات تجريبية داخل الغلاف المعتمد لاختبار الرسائل أثناء العمل خارج التواصل. المهام والمشاريع المعروضة وهمية.</div><div class="work-cards"><article class="work-card"><h2>رسائلك غير المقروءة</h2><strong class="work-number">${state.conversations.reduce((n,c)=>n+unread(c),0)}</strong><p>تصل التنبيهات هنا أيضًا. اضغط الجرس لفتح الرسالة المقصودة.</p><button class="primary" data-page="communication">فتح التواصل</button></article><article class="work-card"><h2>مهامك</h2><strong class="work-number">${state.tasks.length}</strong><p>النقاش المرتبط يظهر هنا وفي التواصل دون إنشاء نسخة أخرى.</p><button data-page="tasks">عرض المهام</button></article><article class="work-card"><h2>مشاريعك</h2><strong class="work-number">${state.conversations.filter(c=>c.type==='project').length}</strong><p>المشاريع التي تملك عضويتها فقط.</p><button data-page="projects">عرض المشاريع</button></article></div>`;return;}
 const rows=currentPage==='tasks'?state.tasks:state.conversations.filter(c=>c.type==='project');$('workPage').innerHTML='<div class="work-cards">'+rows.map(row=>`<article class="work-card"><h2>${esc(row.title)}</h2><p>${currentPage==='tasks'?`${esc(row.status)} · ${esc(person(row.assignee)?.name)} · ${esc(row.due)}`:`${row.members.length} أعضاء · نقاش المشروع موحد`}</p><button class="primary" data-work-discussion="${currentPage==='tasks'?row.conversation:row.id}">فتح النقاش</button>${currentPage==='tasks'&&state.conversations.some(c=>c.id===row.sourceConversation)?`<button class="work-open-dialog" data-conversation="${row.sourceConversation}">الرسالة الأصلية</button>`:''}</article>`).join('')+'</div>'+(rows.length?'':`<div class="empty"><b>لا توجد مهام متاحة بعد</b>أنشئ مهمة من رسالة في التواصل؛ ستظهر هنا مع النقاش نفسه.</div>`);
}
function closeThread(){if(threadRoot&&state){try{store(`thread-draft-${state.me.id}-${threadRoot}`,$('threadInput').value);}catch{}}threadRoot=null;threadFile=null;$('threadAttachmentBar').hidden=true;$('threadDialog').close();$('threadMessages').replaceChildren();heartbeat();}
function openThread(id){const root=state.messages.find(m=>m.id===id&&!m.thread);if(!root)return;const c=state.conversations.find(c=>c.id===root.conversation);if(!c)return;if(active!==c.id)selectConversation(c.id);if(threadRoot!==id)closeThread();threadRoot=id;$('threadInput').value=load(`thread-draft-${state.me.id}-${id}`,'');$('threadSend').disabled=!$('threadInput').value.trim();$('threadError').textContent='';$('threadDialog').showModal();renderThread(true);heartbeat();$('threadInput').focus();}
let threadReading=false;
async function markThreadRead(){if(!threadRoot||!$('threadDialog').open||document.hidden||threadReading)return;const root=threadRoot,who=state.me.id;const latest=Math.max(0,...state.messages.filter(m=>m.thread===root).map(m=>m.seq));if((state.threadReads[root]||0)>=latest)return;threadReading=true;try{await api('action',{action:'read',data:{conversation:active,thread:root,seq:latest}});if(state?.me.id===who){state.threadReads[root]=latest;renderList();renderNotifications();}}catch{}finally{threadReading=false;}}
function renderThread(force=false){if(!threadRoot||!$('threadDialog').open)return;const root=state.messages.find(m=>m.id===threadRoot);if(!root){closeThread();return;}const host=$('threadMessages'),near=host.scrollHeight-host.scrollTop-host.clientHeight<70,top=host.scrollTop;const replies=state.messages.filter(m=>m.thread===threadRoot);const pending=queue().filter(m=>m.reply&&(m.reply===threadRoot||state.messages.find(x=>x.id===m.reply)?.thread===threadRoot)).map(m=>({...m,id:m.clientId,sender:state.me.id,reactions:[],pending:true}));
 host.innerHTML='<div class="thread-root">'+messageHTML(root,true)+'</div>'+[...replies,...pending].map(m=>messageHTML(m,true)).join('');$('threadCount').textContent=replies.length+' ردود';$('followThread').textContent=state.following.includes(threadRoot)?'إيقاف متابعة النقاش':'متابعة النقاش';$('followThread').setAttribute('aria-pressed',String(state.following.includes(threadRoot)));if(force||near){host.scrollTop=host.scrollHeight;markThreadRead();}else host.scrollTop=top;
}
function renderNotifications(){if(!state)return;const count=state.notifications.filter(n=>!n.read).length,unreads=state.conversations.reduce((n,c)=>n+unread(c),0);$('notificationBadge').textContent=count;$('notificationBadge').hidden=!count;$('communicationBadge').textContent=unreads;$('communicationBadge').hidden=!unreads;const mobileBadge=$('mobileCommunicationBadge');mobileBadge.textContent=unreads?` (${unreads})`:'';
 const labels={direct:'رسالة مباشرة',mention:'إشارة إليك',thread:'رد في نقاش تتابعه',announcement:'إعلان',group:'رسالة مجموعة'};
 $('notificationList').innerHTML=[...state.notifications].reverse().map(n=>{const m=state.messages.find(m=>m.id===n.message);return `<button class="notification-row ${n.read?'':'unread'}" data-notification="${n.id}"><strong>${labels[n.kind]} · ${esc(person(m?.sender)?.name)}</strong><p>${state.preferences.preview?esc(m?.body||m?.file?.name||'رسالة جديدة'):'لديك رسالة جديدة'}</p><small>${esc(title(state.conversations.find(c=>c.id===n.conversation)))} · ${time(n.created)}</small></button>`;}).join('')||'<div class="empty">لا توجد إشعارات بعد.</div>';
}
async function openNotification(id){filter='all';$('search').value='';document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('selected',x.dataset.filter==='all'));setPeopleMode(false);const n=state.notifications.find(n=>n.id===id);if(!n)return;const m=state.messages.find(m=>m.id===n.message);$('notificationsDialog').close();await act('notificationRead',{id});selectConversation(n.conversation);if(m?.thread)openThread(m.thread);else if(m){notificationTarget=m.id;renderMessages();const target=document.querySelector(`[data-message="${m.id}"]`);target?.scrollIntoView({block:'center'});target?.classList.add('message-target');}document.querySelector(`[data-toast="${id}"]`)?.remove();}
let audio=null;
function playSound(){try{const A=window.AudioContext||window.webkitAudioContext;if(!A)return;audio??=new A();if(audio.state!=='running')return;const osc=audio.createOscillator(),gain=audio.createGain();osc.frequency.value=660;gain.gain.setValueAtTime(.025,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+.2);osc.connect(gain);gain.connect(audio.destination);osc.start();osc.stop(audio.currentTime+.22);}catch{}}
function showNotification(n){const m=state.messages.find(m=>m.id===n.message),sender=person(m?.sender)?.name||'رسالة جديدة',preview=state.preferences.preview?(m?.body||m?.file?.name||'رسالة جديدة'):'لديك رسالة جديدة';
 const toast=document.createElement('div');toast.className='message-toast';toast.dataset.toast=n.id;toast.innerHTML=`<button data-notification="${n.id}"><strong>${esc(sender)}</strong><span>${esc(preview.slice(0,130))}</span></button><button class="icon" data-toast-close="${n.id}" aria-label="إغلاق التنبيه">×</button>`;$('toastArea').append(toast);while($('toastArea').children.length>3)$('toastArea').firstElementChild.remove();setTimeout(()=>toast.remove(),12000);
 if(state.preferences.sound)playSound();if(document.hidden&&state.preferences.desktop&&'Notification' in window&&Notification.permission==='granted'){const desktop=new Notification(sender,{body:preview.slice(0,130),tag:'atwar-message-'+n.id});desktop.onclick=()=>{window.focus();openNotification(n.id);desktop.close();};}
}
async function processNotifications(){if(notifying||!state)return;if(notificationBaseline===null){notificationBaseline=new Set(state.notifications.map(n=>n.id));return;}const fresh=state.notifications.filter(n=>!notificationBaseline.has(n.id));fresh.forEach(n=>notificationBaseline.add(n.id));if(!fresh.length)return;notifying=true;const who=state.me.id,version=epoch;try{await heartbeat();for(const n of fresh){if(who!==state?.me.id||version!==epoch)break;try{const claim=await api('action',{action:'notificationClaim',data:{id:n.id}});if(claim.show&&who===state?.me.id&&version===epoch)showNotification(n);}catch{notificationBaseline.delete(n.id);}}}finally{notifying=false;}}
function showSettings(){const prefs=state.preferences;$('settingsAvailability').value=$('availability').value;for(const [id,key] of [['soundSetting','sound'],['previewSetting','preview'],['desktopSetting','desktop'],['quietSetting','quiet']])$(id).checked=prefs[key];$('quietStart').value=prefs.start;$('quietEnd').value=prefs.end;$('groupSetting').value=prefs.groups;$('settingsError').textContent='';$('desktopStatus').textContent=!('Notification' in window)?'إشعارات المتصفح غير متاحة في هذه البيئة.':Notification.permission==='granted'?'إذن إشعارات المتصفح متاح.':'يُطلب إذن المتصفح عند تفعيل الخيار وحفظه. لا تشمل هذه التجربة الإشعارات بعد إغلاق المتصفح.';$('settingsDialog').showModal();}
$('peopleTab').onclick=()=>setPeopleMode(true);$('conversationsTab').onclick=()=>setPeopleMode(false);$('peopleSearch').oninput=renderPeople;$('peopleFilter').onchange=renderPeople;
$('availability').onchange=async()=>{try{await act('availability',{status:$('availability').value});heartbeat();}catch(e){notice(e.message);}};
$('notificationButton').onclick=()=>{renderNotifications();$('notificationsDialog').showModal();};$('readNotifications').onclick=()=>act('notificationRead',{all:true}).catch(e=>notice(e.message));$('settingsButton').onclick=showSettings;
for(const id of ['quietStart','quietEnd'])$(id).innerHTML=Array.from({length:24},(_,i)=>`<option value="${i}">${String(i).padStart(2,'0')}:00</option>`).join('');
$('settingsForm').onsubmit=async e=>{e.preventDefault();try{let desktop=$('desktopSetting').checked;if(desktop){if(!('Notification' in window))throw new Error('المتصفح لا يدعم هذه الإشعارات.');const permission=Notification.permission==='granted'?'granted':await Notification.requestPermission();if(permission==='granted'&&Notification.permission!=='granted')throw new Error('هذه البيئة لا تسمح بعرض إشعارات الأجهزة. عطّل الخيار لحفظ بقية الإعدادات.');if(permission!=='granted')throw new Error('لم يُمنح إذن المتصفح؛ يمكنك حفظ بقية الخيارات دون تفعيل إشعارات المتصفح.');}await act('preferences',{sound:$('soundSetting').checked,preview:$('previewSetting').checked,desktop,quiet:$('quietSetting').checked,start:Number($('quietStart').value),end:Number($('quietEnd').value),groups:$('groupSetting').value});await act('availability',{status:$('settingsAvailability').value});$('settingsDialog').close();}catch(e){$('settingsError').textContent=e.message;}};
$('followThread').onclick=()=>act('follow',{conversation:active,message:threadRoot}).catch(e=>$('threadError').textContent=e.message);
$('threadInput').oninput=()=>{$('threadSend').disabled=!$('threadInput').value.trim()&&!threadFile;if(threadRoot){try{store(currentDraftKey(),$('threadInput').value);}catch{}}};
$('threadInput').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();$('threadForm').requestSubmit();}};
$('threadForm').onsubmit=async e=>{e.preventDefault();if(!threadRoot)return;const body=$('threadInput').value.trim();if(!body&&!threadFile)return;const m={conversation:active,body,file:threadFile,reply:threadRoot,mentions:conv().members.filter(id=>id!==state.me.id&&body.includes('@'+person(id).name)),clientId:crypto.randomUUID(),created:new Date().toISOString()};if(threadFile){if(!navigator.onLine){$('threadError').textContent='رفع المرفقات يحتاج اتصالًا. بقي المرفق والنص.';return;}if(busy)return;busy=true;$('threadSend').disabled=true;try{await api('action',{action:'message',data:m});threadFile=null;$('threadAttachmentBar').hidden=true;$('threadInput').value='';store(currentDraftKey(),'');$('threadError').textContent='';await sync();renderThread(true);}catch(err){$('threadError').textContent='لم يُرسل المرفق: '+err.message;$('threadSend').disabled=false;}finally{busy=false;}return;}try{store('outbox-'+state.me.id,[...queue(),m]);threadFile=null;$('threadAttachmentBar').hidden=true;$('threadInput').value='';store(currentDraftKey(),'');$('threadSend').disabled=true;renderThread(true);await flush();}catch(e){$('threadError').textContent=e.message;}};
$('threadAttach').onclick=()=>$('threadFileInput').click();
$('threadFileInput').onchange=async()=>{const f=$('threadFileInput').files[0],root=threadRoot,version=epoch;if(!f)return;try{if(f.size>10*1024*1024)throw new Error('حد الملف ١٠ ميجابايت في التجربة.');const base64=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(f);});if(root!==threadRoot||epoch!==version)return;threadFile={name:f.name,type:attachmentType(f),base64};$('threadAttachmentBar').innerHTML=`<span>مرفق: ${esc(f.name)}</span><button type="button" id="cancelThreadFile" class="icon" aria-label="إزالة المرفق">×</button>`;$('threadAttachmentBar').hidden=false;$('threadSend').disabled=false;}catch(e){$('threadError').textContent=e.message;}finally{$('threadFileInput').value='';}};
$('threadAttachmentBar').onclick=e=>{if(e.target.closest('#cancelThreadFile')){threadFile=null;$('threadAttachmentBar').hidden=true;$('threadSend').disabled=!$('threadInput').value.trim();}};
$('threadMention').onclick=()=>{$('mentionChoices').innerHTML=conv().members.filter(id=>id!==state.me.id).map(id=>`<button class="choice" data-thread-mention="${id}">${esc(person(id).name)}</button>`).join('');$('mentionDialog').showModal();};
$('threadDialog').addEventListener('cancel',e=>{e.preventDefault();closeThread();});$('threadMessages').onscroll=()=>{if($('threadMessages').scrollHeight-$('threadMessages').scrollTop-$('threadMessages').clientHeight<60)markThreadRead();};
document.addEventListener('click',e=>{const b=e.target.closest('[data-thread-mention]');if(b){$('threadInput').value+='@'+person(b.dataset.threadMention).name+' ';$('threadSend').disabled=false;$('mentionDialog').close();$('threadInput').focus();}});
for(const kind of ['pointerdown','keydown'])document.addEventListener(kind,()=>{lastActivity=Date.now();if(state?.preferences.sound){try{const A=window.AudioContext||window.webkitAudioContext;if(A){audio??=new A();if(audio.state==='suspended')audio.resume();}}catch{}}},{passive:true});
document.querySelectorAll('a[data-page]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();navigatePage(a.dataset.page);}));
const mobileNav=document.createElement('nav');mobileNav.className='mobile-system-nav';mobileNav.setAttribute('aria-label','تنقل النظام');mobileNav.innerHTML=Object.entries(pageTitles).map(([page,t])=>`<button data-page="${page}" class="${page==='communication'?'active':''}">${t[0]}${page==='communication'?'<span id="mobileCommunicationBadge"></span>':''}</button>`).join('');document.querySelector('.lab-main .atwar-topbar').after(mobileNav);

if(sessionChannel)sessionChannel.onmessage=async()=>{epoch++;events?.close();if(threadRoot&&state){try{store(`thread-draft-${state.me.id}-${threadRoot}`,$('threadInput').value);}catch{}}state=null;active=null;threadRoot=null;threadFile=null;file=null;reply=null;mentions=[];sourceMessage=null;notificationTarget=null;detailTask=null;notificationBaseline=null;for(const id of ['messages','conversationFiles','conversations','details','peopleList','notificationList','toastArea','threadMessages','mentionChoices','linkChoices','memberChoices'])$(id).replaceChildren();for(const id of ['threadDialog','newDialog','taskDialog','mentionDialog','linkDialog','notificationsDialog','settingsDialog'])$(id).close();$('messageInput').value='';$('identity').textContent='جارٍ تحديث الحساب…';$('details').hidden=true;$('layout').classList.remove('chat-open','with-details');while(loading)await new Promise(r=>setTimeout(r,20));await sync();if(state){$('account').value=state.me.id;selectConversation(active,innerWidth>700);connect();}};
try{const accounts=await api('accounts');$('account').innerHTML=accounts.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');await sync();if(!state)throw new Error('يلزم تسجيل الدخول إلى النظام.');else{$('account').value=state.me.id;const target=notificationTarget;selectConversation(active,innerWidth>700);if(target){const message=state.messages.find(m=>m.id===target);if(message?.thread)openThread(message.thread);notificationTarget=target;renderMessages();document.querySelector('[data-message="'+CSS.escape(target)+'"]')?.scrollIntoView({block:'center'});}heartbeat();connect();}}catch(e){await sync();notice(e.message||'يلزم تسجيل الدخول إلى النظام.');}


function renderFiles(){if(!state||!active)return;const files=state.messages.filter(m=>m.conversation===active&&m.file).sort((a,b)=>b.seq-a.seq);$('conversationFiles').innerHTML=files.length?'<h3>ملفات المحادثة</h3>'+files.map(m=>`<a class="shared-file" href="#" data-trial-file="${m.file.id}" download="${esc(m.file.name)}"><span class="file-symbol">↧</span><span><strong>${esc(m.file.name)}</strong><small>${esc(person(m.sender)?.name)} · ${day(m.created)} · ${Math.ceil(m.file.size/1024)} كيلوبايت</small></span></a>`).join(''):'<div class="empty">لا توجد ملفات في هذه المحادثة بعد.</div>';}

document.addEventListener('click',async e=>{const a=e.target.closest('[data-trial-file]');if(!a)return;e.preventDefault();try{const f=await api('file',{id:a.dataset.trialFile});const bytes=Uint8Array.from(atob(f.base64),c=>c.charCodeAt(0));const url=URL.createObjectURL(new Blob([bytes],{type:f.type}));const link=document.createElement('a');link.href=url;link.download=f.name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(err){notice(err.message);}});
